<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_04fUzhiService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.04fUzhi' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';

        return $container->privates['.messenger.handler_descriptor.04fUzhi'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->privates['scheduler.messenger.service_call_message_handler'] ?? $container->load('getScheduler_Messenger_ServiceCallMessageHandlerService')), []);
    }
}
