<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackgroundProcessManagerService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Tool\BackgroundProcessManager' shared service.
     *
     * @return \Ineersa\CodingAgent\Tool\BackgroundProcessManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Tool/BackgroundProcessManager.php';

        $a = ($container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcess\\ProcessStore'] ?? $container->load('getProcessStoreService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcessManager'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcessManager'];
        }
        $b = ($container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcess\\ProcessLifecycle'] ?? $container->load('getProcessLifecycleService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcessManager'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcessManager'];
        }

        $instance = new \Ineersa\CodingAgent\Tool\BackgroundProcessManager($a, $b, ($container->privates['Ineersa\\CodingAgent\\Config\\BackgroundProcessConfig'] ?? $container->load('getBackgroundProcessConfigService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcessManager'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcessManager'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcessManager'] = $instance;
    }
}
