<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBeforeProviderRequestSubscriberService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\AgentCore\Infrastructure\SymfonyAi\BeforeProviderRequestSubscriber' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Infrastructure\SymfonyAi\BeforeProviderRequestSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Infrastructure/SymfonyAi/BeforeProviderRequestSubscriber.php';

        return $container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\BeforeProviderRequestSubscriber'] = new \Ineersa\AgentCore\Infrastructure\SymfonyAi\BeforeProviderRequestSubscriber(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Ineersa\\CodingAgent\\Config\\CompatRequestShaper'] ?? $container->load('getCompatRequestShaperService'));
        }, 1));
    }
}
