<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_ArgumentResolverService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the public 'console.argument_resolver' shared service.
     *
     * @return \Symfony\Component\Console\ArgumentResolver\TraceableArgumentResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ArgumentResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/TraceableArgumentResolver.php';

        return $container->services['console.argument_resolver'] = new \Symfony\Component\Console\ArgumentResolver\TraceableArgumentResolver(($container->privates['debug.console.argument_resolver.inner'] ?? $container->load('getDebug_Console_ArgumentResolver_InnerService')), ($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true)));
    }
}
