<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHookSubscriberRegistryService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\AgentCore\Application\Handler\HookSubscriberRegistry' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Handler\HookSubscriberRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Handler/HookSubscriberRegistry.php';

        return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\HookSubscriberRegistry'] = new \Ineersa\AgentCore\Application\Handler\HookSubscriberRegistry(new RewindableGenerator(fn () => new \EmptyIterator(), 0));
    }
}
