<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInMemoryPromptStateStoreService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\AgentCore\Infrastructure\Storage\InMemoryPromptStateStore' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Infrastructure\Storage\InMemoryPromptStateStore
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Contract/PromptStateStoreInterface.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Infrastructure/Storage/InMemoryPromptStateStore.php';

        return $container->privates['Ineersa\\AgentCore\\Infrastructure\\Storage\\InMemoryPromptStateStore'] = new \Ineersa\AgentCore\Infrastructure\Storage\InMemoryPromptStateStore();
    }
}
