<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogSearchCommandService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\CLI\Log\LogSearchCommand' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\CLI\Log\LogSearchCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/CLI/Log/LogSearchCommand.php';

        return $container->privates['Ineersa\\CodingAgent\\CLI\\Log\\LogSearchCommand'] = new \Ineersa\CodingAgent\CLI\Log\LogSearchCommand(($container->privates['Ineersa\\CodingAgent\\Logging\\LogReaderFactory'] ?? $container->load('getLogReaderFactoryService')));
    }
}
