<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModelControlListenerService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\Tui\Listener\ModelControlListener' shared autowired service.
     *
     * @return \Ineersa\Tui\Listener\ModelControlListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Tui/Listener/TuiListenerRegistrar.php';
        include_once \dirname(__DIR__, 4).'/src/Tui/Listener/ModelControlListener.php';
        include_once \dirname(__DIR__, 4).'/src/Tui/Command/SlashCommandRegistry.php';

        return $container->privates['Ineersa\\Tui\\Listener\\ModelControlListener'] = new \Ineersa\Tui\Listener\ModelControlListener(($container->privates['Ineersa\\CodingAgent\\Config\\ModelSelectionService'] ?? $container->load('getModelSelectionServiceService')), ($container->privates['Ineersa\\Tui\\Command\\SlashCommandRegistry'] ??= new \Ineersa\Tui\Command\SlashCommandRegistry()), ($container->privates['Ineersa\\CodingAgent\\Config\\AppConfig'] ?? self::getAppConfigService($container)), ($container->privates['Ineersa\\Tui\\Picker\\ModelPickerController'] ?? $container->load('getModelPickerControllerService')), ($container->privates['Ineersa\\Tui\\Picker\\FavoritePickerController'] ?? $container->load('getFavoritePickerControllerService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
