<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModelResolverService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Config\ModelResolver' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Config\ModelResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Config/ModelResolver.php';

        $a = ($container->privates['Ineersa\\CodingAgent\\Config\\AppConfig'] ?? self::getAppConfigService($container));

        if (isset($container->privates['Ineersa\\CodingAgent\\Config\\ModelResolver'])) {
            return $container->privates['Ineersa\\CodingAgent\\Config\\ModelResolver'];
        }
        $b = ($container->privates['Ineersa\\CodingAgent\\Config\\SessionMetadataStore'] ?? $container->load('getSessionMetadataStoreService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Config\\ModelResolver'])) {
            return $container->privates['Ineersa\\CodingAgent\\Config\\ModelResolver'];
        }

        $instance = new \Ineersa\CodingAgent\Config\ModelResolver($a, $b);

        if (isset($container->privates['Ineersa\\CodingAgent\\Config\\ModelResolver'])) {
            return $container->privates['Ineersa\\CodingAgent\\Config\\ModelResolver'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Config\\ModelResolver'] = $instance;
    }
}
