<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonolog_LoggerService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'monolog.logger' shared service.
     *
     * @return \Monolog\Logger
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Monolog\Logger('app');

        if (isset($container->privates['monolog.logger'])) {
            return $container->privates['monolog.logger'];
        }

        $container->privates['monolog.logger'] = $instance;

        $instance->useMicrosecondTimestamps(true);
        $instance->pushHandler(($container->privates['Ineersa\\CodingAgent\\Logging\\HatfieldRotatingLogHandler'] ?? self::getHatfieldRotatingLogHandlerService($container)));
        $instance->pushProcessor(($container->privates['Ineersa\\CodingAgent\\Logging\\LogContextProcessor'] ??= new \Ineersa\CodingAgent\Logging\LogContextProcessor()));

        return $instance;
    }
}
