<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonolog_Logger_ConsoleService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'monolog.logger.console' shared service.
     *
     * @return \Monolog\Logger
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['monolog.logger.console'] = $instance = new \Monolog\Logger('console');

        $instance->pushProcessor(($container->privates['Ineersa\\CodingAgent\\Logging\\LogContextProcessor'] ??= new \Ineersa\CodingAgent\Logging\LogContextProcessor()));

        return $instance;
    }
}
