<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOutputCapLlmTransformHookService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Tool\OutputCapLlmTransformHook' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Tool\OutputCapLlmTransformHook
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Contract/Hook/TransformContextHookInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Tool/OutputCapLlmTransformHook.php';

        return $container->privates['Ineersa\\CodingAgent\\Tool\\OutputCapLlmTransformHook'] = new \Ineersa\CodingAgent\Tool\OutputCapLlmTransformHook(($container->privates['Ineersa\\CodingAgent\\Tool\\OutputCap'] ?? $container->load('getOutputCapService')));
    }
}
