<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromptHistoryListenerService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\Tui\Listener\PromptHistoryListener' shared autowired service.
     *
     * @return \Ineersa\Tui\Listener\PromptHistoryListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Tui/Listener/TuiListenerRegistrar.php';
        include_once \dirname(__DIR__, 4).'/src/Tui/Listener/PromptHistoryListener.php';

        return $container->privates['Ineersa\\Tui\\Listener\\PromptHistoryListener'] = new \Ineersa\Tui\Listener\PromptHistoryListener();
    }
}
