<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReplayServiceService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\AgentCore\Application\Handler\ReplayService' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Handler\ReplayService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Handler/ReplayService.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Contract/PromptStateStoreInterface.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Infrastructure/Storage/InMemoryPromptStateStore.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Handler/RunMetrics.php';

        $a = ($container->privates['Ineersa\\CodingAgent\\Session\\SessionRunEventStore'] ?? $container->load('getSessionRunEventStoreService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Handler\\ReplayService'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\ReplayService'];
        }

        $instance = new \Ineersa\AgentCore\Application\Handler\ReplayService($a, ($container->privates['Ineersa\\AgentCore\\Infrastructure\\Storage\\InMemoryPromptStateStore'] ??= new \Ineersa\AgentCore\Infrastructure\Storage\InMemoryPromptStateStore()), ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunMetrics'] ??= new \Ineersa\AgentCore\Application\Handler\RunMetrics()), ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunTracer'] ?? $container->load('getRunTracerService')));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Handler\\ReplayService'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\ReplayService'];
        }

        return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\ReplayService'] = $instance;
    }
}
