<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSlashCommandCompletionProviderService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\Tui\Completion\SlashCommandCompletionProvider' shared autowired service.
     *
     * @return \Ineersa\Tui\Completion\SlashCommandCompletionProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Tui/Completion/CompletionProvider.php';
        include_once \dirname(__DIR__, 4).'/src/Tui/Completion/SlashCommandCompletionProvider.php';
        include_once \dirname(__DIR__, 4).'/src/Tui/Command/SlashCommandRegistry.php';

        return $container->privates['Ineersa\\Tui\\Completion\\SlashCommandCompletionProvider'] = new \Ineersa\Tui\Completion\SlashCommandCompletionProvider(($container->privates['Ineersa\\Tui\\Command\\SlashCommandRegistry'] ??= new \Ineersa\Tui\Command\SlashCommandRegistry()));
    }
}
