<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionMetadataStoreService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Config\SessionMetadataStore' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Config\SessionMetadataStore
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Config/SessionMetadataStore.php';

        $a = ($container->privates['Ineersa\\CodingAgent\\Session\\HatfieldSessionStore'] ?? $container->load('getHatfieldSessionStoreService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Config\\SessionMetadataStore'])) {
            return $container->privates['Ineersa\\CodingAgent\\Config\\SessionMetadataStore'];
        }

        $instance = new \Ineersa\CodingAgent\Config\SessionMetadataStore($a);

        if (isset($container->privates['Ineersa\\CodingAgent\\Config\\SessionMetadataStore'])) {
            return $container->privates['Ineersa\\CodingAgent\\Config\\SessionMetadataStore'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Config\\SessionMetadataStore'] = $instance;
    }
}
