<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JrLpenGService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private '.service_locator.jrLpenG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jrLpenG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'default' => ['privates', 'scheduler.provider.default', 'getScheduler_Provider_DefaultService', true],
        ], [
            'default' => 'Symfony\\Component\\Scheduler\\Schedule',
        ]);
    }
}
