<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_10bFTtqService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.10bFTtq' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunOrchestrator'] ?? $container->load('getRunOrchestratorService'));

        if (isset($container->privates['.messenger.handler_descriptor.10bFTtq'])) {
            return $container->privates['.messenger.handler_descriptor.10bFTtq'];
        }

        $instance = new \Symfony\Component\Messenger\Handler\HandlerDescriptor($a->onApplyCommand(...), ['method' => 'onApplyCommand', 'bus' => 'agent.command.bus']);

        if (isset($container->privates['.messenger.handler_descriptor.10bFTtq'])) {
            return $container->privates['.messenger.handler_descriptor.10bFTtq'];
        }

        return $container->privates['.messenger.handler_descriptor.10bFTtq'] = $instance;
    }
}
