<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackgroundProcessStatusCheckerService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Tool\ToolQuestion\BackgroundProcessStatusChecker' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Tool\ToolQuestion\BackgroundProcessStatusChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcessManager'] ?? $container->load('getBackgroundProcessManagerService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\BackgroundProcessStatusChecker'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\BackgroundProcessStatusChecker'];
        }

        $instance = new \Ineersa\CodingAgent\Tool\ToolQuestion\BackgroundProcessStatusChecker($a);

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\BackgroundProcessStatusChecker'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\BackgroundProcessStatusChecker'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\BackgroundProcessStatusChecker'] = $instance;
    }
}
