<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandMailboxPolicyService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\AgentCore\Application\Pipeline\CommandMailboxPolicy' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Pipeline\CommandMailboxPolicy
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\CommandMailboxPolicy'] = new \Ineersa\AgentCore\Application\Pipeline\CommandMailboxPolicy(($container->privates['Ineersa\\AgentCore\\Infrastructure\\Storage\\InMemoryCommandStore'] ??= new \Ineersa\AgentCore\Infrastructure\Storage\InMemoryCommandStore()), ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\CommandRouter'] ?? $container->load('getCommandRouterService')));
    }
}
