<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCodexAuthCommand_Command_LazyService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private '.Ineersa\CodingAgent\CLI\Auth\CodexAuthCommand.command.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.Ineersa\\CodingAgent\\CLI\\Auth\\CodexAuthCommand.command.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('auth:codex', [], 'Authenticate with OpenAI Codex subscription (OAuth PKCE)', false, #[\Closure(name: 'Ineersa\\CodingAgent\\CLI\\Auth\\CodexAuthCommand.command', class: 'Symfony\\Component\\Console\\Command\\Command')] fn (): \Symfony\Component\Console\Command\Command => ($container->privates['Ineersa\\CodingAgent\\CLI\\Auth\\CodexAuthCommand.command'] ?? $container->load('getCodexAuthCommand_CommandService')));
    }
}
