<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExtensionToolRegistryBridgeService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Extension\ExtensionToolRegistryBridge' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Extension\ExtensionToolRegistryBridge
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Tool\\ToolRegistry'] ?? $container->load('getToolRegistryService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionToolRegistryBridge'])) {
            return $container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionToolRegistryBridge'];
        }
        $b = ($container->privates['Ineersa\\CodingAgent\\Config\\AppConfig'] ?? self::getAppConfigService($container));

        if (isset($container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionToolRegistryBridge'])) {
            return $container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionToolRegistryBridge'];
        }

        $instance = new \Ineersa\CodingAgent\Extension\ExtensionToolRegistryBridge($a, ($container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionHookRegistry'] ??= new \Ineersa\CodingAgent\Extension\ExtensionHookRegistry()), $b);

        if (isset($container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionToolRegistryBridge'])) {
            return $container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionToolRegistryBridge'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionToolRegistryBridge'] = $instance;
    }
}
