<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRunOrchestratorService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\AgentCore\Application\Pipeline\RunOrchestrator' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Pipeline\RunOrchestrator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunMessageProcessor'] ?? $container->load('getRunMessageProcessorService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunOrchestrator'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunOrchestrator'];
        }

        $instance = new \Ineersa\AgentCore\Application\Pipeline\RunOrchestrator($a, ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunTracer'] ?? $container->load('getRunTracerService')));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunOrchestrator'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunOrchestrator'];
        }

        return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunOrchestrator'] = $instance;
    }
}
