<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRuntimeEventTranslatorService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Runtime\Protocol\RuntimeEventTranslator' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Runtime\Protocol\RuntimeEventTranslator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['Ineersa\\CodingAgent\\Runtime\\Protocol\\RuntimeEventTranslator'])) {
            return $container->privates['Ineersa\\CodingAgent\\Runtime\\Protocol\\RuntimeEventTranslator'];
        }

        $instance = new \Ineersa\CodingAgent\Runtime\Protocol\RuntimeEventTranslator($a);

        if (isset($container->privates['Ineersa\\CodingAgent\\Runtime\\Protocol\\RuntimeEventTranslator'])) {
            return $container->privates['Ineersa\\CodingAgent\\Runtime\\Protocol\\RuntimeEventTranslator'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Runtime\\Protocol\\RuntimeEventTranslator'] = $instance;
    }
}
