<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStringTemplateRendererService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Symfony\AI\Platform\Message\TemplateRenderer\StringTemplateRenderer' shared autowired service.
     *
     * @return \Symfony\AI\Platform\Message\TemplateRenderer\StringTemplateRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Symfony\\AI\\Platform\\Message\\TemplateRenderer\\StringTemplateRenderer'] = new \Symfony\AI\Platform\Message\TemplateRenderer\StringTemplateRenderer();
    }
}
