<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionPickerControllerService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\Tui\Picker\SessionPickerController' shared autowired service.
     *
     * @return \Ineersa\Tui\Picker\SessionPickerController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\Tui\\Picker\\SessionPickerController'] = new \Ineersa\Tui\Picker\SessionPickerController(($container->privates['Ineersa\\CodingAgent\\Session\\HatfieldSessionStore'] ?? $container->load('getHatfieldSessionStoreService')), ($container->privates['Ineersa\\Tui\\Application\\TuiSessionSwitchService'] ?? $container->load('getTuiSessionSwitchServiceService')));
    }
}
