<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSkillContextRendererService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Skills\SkillContextRenderer' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Skills\SkillContextRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\CodingAgent\\Skills\\SkillContextRenderer'] = new \Ineersa\CodingAgent\Skills\SkillContextRenderer();
    }
}
