<?php

declare(strict_types=1);

namespace Ineersa\CodingAgent\Tests\Tool\Support;

use Ineersa\CodingAgent\Config\AgentsConfig;
use Ineersa\CodingAgent\Config\BashToolConfig;
use Ineersa\CodingAgent\Tool\HatfieldToolProviderInterface;
use Ineersa\CodingAgent\Tool\RawAwareToolCallArgumentResolver;
use Ineersa\CodingAgent\Tool\RegistryBackedToolbox;
use Ineersa\CodingAgent\Tool\Schema\BashTimeoutSchemaProvider;
use Ineersa\CodingAgent\Tool\Schema\SubagentTasksSchemaProvider;
use Ineersa\CodingAgent\Tool\ToolRegistry;
use Symfony\AI\Agent\Toolbox\ToolCallArgumentResolver;
use Symfony\AI\Platform\Contract\JsonSchema\Describer\Describer;
use Symfony\AI\Platform\Contract\JsonSchema\Describer\MethodDescriber;
use Symfony\AI\Platform\Contract\JsonSchema\Describer\PropertyInfoDescriber;
use Symfony\AI\Platform\Contract\JsonSchema\Describer\SchemaAttributeDescriber;
use Symfony\AI\Platform\Contract\JsonSchema\Describer\SerializerDescriber;
use Symfony\AI\Platform\Contract\JsonSchema\Describer\TypeInfoDescriber;
use Symfony\AI\Platform\Contract\JsonSchema\Describer\ValidatorConstraintsDescriber;
use Symfony\AI\Platform\Contract\JsonSchema\Factory;

/**
 * Builds the native provider-visible parameter schema for one real tool
 * definition through the production RegistryBackedToolbox wiring.
 *
 * Typed DTO tools yield the flat DTO-field schema (the single DTO parameter's
 * object schema hoisted to the Tool root) generated by Symfony AI's JsonSchema
 * Factory; raw tools yield their flat runtime schema.
 *
 * The schema describer chain mirrors config/services.yaml (default Symfony
 * AI chain plus the provider-aware SchemaAttributeDescriber) so DTOs using
 * #[Schema(provider: ...)] for settings-derived bounds resolve here with
 * default config values.
 */
final class NativeToolSchemaProbe
{
    /**
     * @return array<string, mixed>
     */
    public static function for(HatfieldToolProviderInterface $provider): array
    {
        $toolbox = new RegistryBackedToolbox(
            new ToolRegistry([$provider]),
            new RawAwareToolCallArgumentResolver(new ToolCallArgumentResolver()),
            schemaFactory: self::schemaFactory(),
        );

        $tools = $toolbox->getTools();

        return [] === $tools ? [] : ($tools[0]->getParameters() ?? []);
    }

    /**
     * Provider-aware JsonSchema Factory mirroring config/services.yaml.
     *
     * Uses default config values for the settings-derived schema fragments;
     * execution-side tests that need matching bounds inject their own
     * validator with the same config instead.
     */
    public static function schemaFactory(): Factory
    {
        return new Factory(new Describer([
            new SerializerDescriber(),
            new TypeInfoDescriber(),
            new MethodDescriber(),
            new PropertyInfoDescriber(),
            new ValidatorConstraintsDescriber(),
            new SchemaAttributeDescriber([
                BashTimeoutSchemaProvider::class => new BashTimeoutSchemaProvider(new BashToolConfig()),
                SubagentTasksSchemaProvider::class => new SubagentTasksSchemaProvider(new AgentsConfig()),
            ]),
        ]));
    }
}
