<?php

declare(strict_types=1);

namespace Ineersa\CodingAgent\Tests\Tool\Support;

use Ineersa\CodingAgent\Tool\HatfieldToolProviderInterface;
use Ineersa\CodingAgent\Tool\RawAwareToolCallArgumentResolver;
use Ineersa\CodingAgent\Tool\RegistryBackedToolbox;
use Ineersa\CodingAgent\Tool\ToolRegistry;
use Symfony\AI\Agent\Toolbox\ToolCallArgumentResolver;

/**
 * Builds the native provider-visible parameter schema for one real tool
 * definition through the production RegistryBackedToolbox wiring.
 *
 * Typed DTO tools yield the nested {arguments: {...}} shape generated by
 * Symfony AI's ReflectionToolFactory; raw tools yield their flat schema.
 */
final class NativeToolSchemaProbe
{
    /**
     * @return array<string, mixed>
     */
    public static function for(HatfieldToolProviderInterface $provider): array
    {
        $toolbox = new RegistryBackedToolbox(
            new ToolRegistry([$provider]),
            new RawAwareToolCallArgumentResolver(new ToolCallArgumentResolver()),
        );

        $tools = $toolbox->getTools();

        return [] === $tools ? [] : ($tools[0]->getParameters() ?? []);
    }
}
