<?php

declare(strict_types=1);

namespace Symfony\AI\Platform\Bridge\OpenAICodex;

/**
 * Whether Codex correlation IDs were caller-supplied or synthesized for routing.
 */
enum CodexCorrelationProvenance
{
    /** UUIDv7 generated by Hatfield when no explicit run_id or prompt_cache_key is present. */
    case Generated;

    /** Caller supplied options['provider_cache_key'] (persisted Hatfield session identity). */
    case ExplicitProviderCacheKey;

    /** Caller supplied options['run_id']. */
    case ExplicitRunId;

    /** Caller supplied payload prompt_cache_key (non-empty). */
    case ExplicitPromptCacheKey;
}
