<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_9JusjcHService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.9JusjcH' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Config\\ToolSettings'] ?? $container->load('getToolSettingsService'));

        if (isset($container->privates['.messenger.handler_descriptor.9JusjcH'])) {
            return $container->privates['.messenger.handler_descriptor.9JusjcH'];
        }
        $b = ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'));

        if (isset($container->privates['.messenger.handler_descriptor.9JusjcH'])) {
            return $container->privates['.messenger.handler_descriptor.9JusjcH'];
        }

        $instance = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Ineersa\AgentCore\Application\Handler\ExecuteToolCallWorker(\Ineersa\AgentCore\Application\Handler\ToolExecutor::fromSettings($a, new \Ineersa\AgentCore\Application\Handler\ToolExecutionResultStore(), ($container->privates['Ineersa\\CodingAgent\\Tool\\RegistryBackedToolbox'] ?? $container->load('getRegistryBackedToolboxService')), NULL, ($container->privates['Ineersa\\AgentCore\\Application\\Tool\\StackToolExecutionContextAccessor'] ??= new \Ineersa\AgentCore\Application\Tool\StackToolExecutionContextAccessor()), ($container->privates['Ineersa\\CodingAgent\\Tool\\CodingAgentToolSetResolver'] ?? $container->load('getCodingAgentToolSetResolverService'))), $b, ($container->privates['Ineersa\\CodingAgent\\Session\\SessionRunStore'] ?? $container->load('getSessionRunStoreService')), ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunMetrics'] ??= new \Ineersa\AgentCore\Application\Handler\RunMetrics()), ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunTracer'] ?? $container->load('getRunTracerService'))), ['bus' => 'agent.execution.bus', 'method' => '__invoke']);

        if (isset($container->privates['.messenger.handler_descriptor.9JusjcH'])) {
            return $container->privates['.messenger.handler_descriptor.9JusjcH'];
        }

        return $container->privates['.messenger.handler_descriptor.9JusjcH'] = $instance;
    }
}
