<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Console_ValidateQuestionInputListenerService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private '.console.validate_question_input_listener' shared service.
     *
     * @return \Symfony\Component\Console\EventListener\ValidateQuestionInputListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['validator'] ?? self::getValidatorService($container));

        if (isset($container->privates['.console.validate_question_input_listener'])) {
            return $container->privates['.console.validate_question_input_listener'];
        }

        $instance = new \Symfony\Component\Console\EventListener\ValidateQuestionInputListener($a);

        if (isset($container->privates['.console.validate_question_input_listener'])) {
            return $container->privates['.console.validate_question_input_listener'];
        }

        return $container->privates['.console.validate_question_input_listener'] = $instance;
    }
}
