<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgentCommand_CommandService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\CLI\AgentCommand.command' shared service.
     *
     * @return \Symfony\Component\Console\Command\Command
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Ineersa\\CodingAgent\\CLI\\AgentCommand.command'] = $instance = new \Symfony\Component\Console\Command\Command();

        $a = ($container->privates['Ineersa\\CodingAgent\\Runtime\\InProcess\\InProcessAgentSessionClient'] ?? $container->load('getInProcessAgentSessionClientService'));
        $b = new \Ineersa\CodingAgent\Runtime\Process\RuntimeProcessConfig(new \Ineersa\CodingAgent\Runtime\Process\ChainExecutableLocator(new \Ineersa\CodingAgent\Runtime\Process\ConfigExecutableLocator($container->getEnv('default:kernel.project_dir:string:HATFIELD_CWD')), new \Ineersa\CodingAgent\Runtime\Process\PharExecutableLocator(), new \Ineersa\CodingAgent\Runtime\Process\SourceTreeExecutableLocator('phar:///home/ineersa/projects/agent-core-worktrees/maint-01-test-suite-maintenance-isolation-cleanup-flaky-gates/var/tmp/phar/hatfield.phar')), $container->getEnv('default:kernel.project_dir:string:HATFIELD_CWD'));
        $c = ($container->privates['Ineersa\\CodingAgent\\Session\\HatfieldSessionStore'] ?? $container->load('getHatfieldSessionStoreService'));
        $d = ($container->privates['Ineersa\\CodingAgent\\Config\\AppConfig'] ?? self::getAppConfigService($container));
        $e = ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'));
        $f = ($container->privates['Ineersa\\Tui\\Transcript\\TranscriptBlockFactory'] ??= new \Ineersa\Tui\Transcript\TranscriptBlockFactory());
        $g = ($container->privates['Ineersa\\CodingAgent\\Runtime\\Contract\\RuntimeExceptionBoundary'] ?? $container->load('getRuntimeExceptionBoundaryService'));
        $h = new \Ineersa\CodingAgent\Runtime\Controller\RuntimeEventEmitter($a, $g, $e);
        $i = ($container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcessManager'] ?? $container->load('getBackgroundProcessManagerService'));

        $instance->setCode((new \Ineersa\CodingAgent\CLI\AgentCommand($a, new \Ineersa\CodingAgent\Runtime\Process\JsonlProcessAgentSessionClient($b), new \Ineersa\Tui\Application\InteractiveMode($c, new \Ineersa\Tui\Application\ThemeFactory($d, new \Ineersa\Tui\Theme\ThemeRegistry($d, ($container->privates['Ineersa\\CodingAgent\\Config\\AppResourceLocator'] ??= new \Ineersa\CodingAgent\Config\AppResourceLocator('phar:///home/ineersa/projects/agent-core-worktrees/maint-01-test-suite-maintenance-isolation-cleanup-flaky-gates/var/tmp/phar/hatfield.phar')), $e)), new \Ineersa\Tui\Application\SessionInitializer($c, ($container->privates['Ineersa\\CodingAgent\\Session\\SessionRunEventStore'] ?? $container->load('getSessionRunEventStoreService')), ($container->privates['Ineersa\\CodingAgent\\Runtime\\Protocol\\RuntimeEventMapper'] ?? $container->load('getRuntimeEventMapperService')), ($container->privates['Ineersa\\CodingAgent\\Runtime\\ProjectionPipeline\\TranscriptProjector'] ?? $container->load('getTranscriptProjectorService')), $f, $e), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Ineersa\\CodingAgent\\CLI\\FileMentionIndexStartupListener'] ?? $container->load('getFileMentionIndexStartupListenerService'));
            yield 1 => ($container->privates['Ineersa\\Tui\\Listener\\CancelListener'] ?? $container->load('getCancelListenerService'));
            yield 2 => ($container->privates['Ineersa\\Tui\\Listener\\CompletionListener'] ?? $container->load('getCompletionListenerService'));
            yield 3 => ($container->privates['Ineersa\\Tui\\Listener\\CopyCommandRegistrar'] ?? $container->load('getCopyCommandRegistrarService'));
            yield 4 => ($container->privates['Ineersa\\Tui\\Listener\\CtrlCInputInterceptor'] ??= new \Ineersa\Tui\Listener\CtrlCInputInterceptor());
            yield 5 => ($container->privates['Ineersa\\Tui\\Listener\\FooterStateListener'] ?? $container->load('getFooterStateListenerService'));
            yield 6 => ($container->privates['Ineersa\\Tui\\Listener\\ModelControlListener'] ?? $container->load('getModelControlListenerService'));
            yield 7 => ($container->privates['Ineersa\\Tui\\Listener\\PromptHistoryListener'] ??= new \Ineersa\Tui\Listener\PromptHistoryListener());
            yield 8 => ($container->privates['Ineersa\\Tui\\Listener\\QuitListener'] ??= new \Ineersa\Tui\Listener\QuitListener());
            yield 9 => ($container->privates['Ineersa\\Tui\\Listener\\SessionCommandRegistrar'] ?? $container->load('getSessionCommandRegistrarService'));
            yield 10 => ($container->privates['Ineersa\\Tui\\Listener\\SubmitListener'] ?? $container->load('getSubmitListenerService'));
            yield 11 => ($container->privates['Ineersa\\Tui\\Listener\\TickPollListener'] ?? $container->load('getTickPollListenerService'));
        }, 12), new \Ineersa\Tui\Editor\PromptEditor(), $f, $e, ($container->privates['Ineersa\\Tui\\Application\\TuiSessionSwitchService'] ?? $container->load('getTuiSessionSwitchServiceService'))), $c, ($container->privates['Ineersa\\CodingAgent\\Skills\\SkillsConfig'] ??= new \Ineersa\CodingAgent\Skills\SkillsConfig()), $e, new \Ineersa\CodingAgent\Migrations\StartupDatabaseMigrator(new \Ineersa\CodingAgent\Migrations\ApplicationMigrationExecutor(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), $e), $e), new \Ineersa\CodingAgent\Runtime\Controller\HeadlessController(new \Ineersa\CodingAgent\Runtime\Controller\ConsumerSupervisor($e, $b), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), $e, ($container->privates['Ineersa\\CodingAgent\\Config\\ToolSettings'] ?? $container->load('getToolSettingsService')), $g, $h, 0, $i, new \Ineersa\CodingAgent\Runtime\Controller\ToolQuestionPoller(($container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\ToolQuestionStore'] ?? $container->load('getToolQuestionStoreService')), $h, $e), new \Ineersa\CodingAgent\Runtime\Controller\BackgroundProcessCompletionPoller(($container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcess\\ProcessStore'] ?? $container->load('getProcessStoreService')), $i, $a, $h, $e, $container->getEnv('HATFIELD_SESSION_ID'))), ($container->privates['Ineersa\\CodingAgent\\Tool\\ToolRegistry'] ?? $container->load('getToolRegistryService'))))->__invoke(...));
        $instance->setName('agent');
        $instance->setDescription('Agent session — TUI (default) or headless JSONL runtime');

        return $instance;
    }
}
