<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgent_Command_Bus_Middleware_SendMessageService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'agent.command.bus.middleware.send_message' shared service.
     *
     * @return \Symfony\Component\Messenger\Middleware\SendMessageMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['messenger.senders_locator'] ?? $container->load('getMessenger_SendersLocatorService'));

        if (isset($container->privates['agent.command.bus.middleware.send_message'])) {
            return $container->privates['agent.command.bus.middleware.send_message'];
        }
        $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['agent.command.bus.middleware.send_message'])) {
            return $container->privates['agent.command.bus.middleware.send_message'];
        }

        $instance = new \Symfony\Component\Messenger\Middleware\SendMessageMiddleware($a, $b, true);

        if (isset($container->privates['agent.command.bus.middleware.send_message'])) {
            return $container->privates['agent.command.bus.middleware.send_message'];
        }

        $container->privates['agent.command.bus.middleware.send_message'] = $instance;

        $instance->setLogger(($container->privates['monolog.logger.messenger'] ?? $container->load('getMonolog_Logger_MessengerService')));

        return $instance;
    }
}
