<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplyCommandHandlerService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\AgentCore\Application\Pipeline\ApplyCommandHandler' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Pipeline\ApplyCommandHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\ApplyCommandHandler'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\ApplyCommandHandler'];
        }

        $instance = new \Ineersa\AgentCore\Application\Pipeline\ApplyCommandHandler(($container->privates['Ineersa\\AgentCore\\Infrastructure\\Storage\\InMemoryCommandStore'] ??= new \Ineersa\AgentCore\Infrastructure\Storage\InMemoryCommandStore()), ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\CommandRouter'] ?? $container->load('getCommandRouterService')), ($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\CommandMailboxPolicy'] ?? $container->load('getCommandMailboxPolicyService')), ($container->privates['Ineersa\\AgentCore\\Domain\\Event\\EventFactory'] ??= new \Ineersa\AgentCore\Domain\Event\EventFactory()), ($container->privates['Ineersa\\AgentCore\\Domain\\Message\\AgentMessageNormalizer'] ??= new \Ineersa\AgentCore\Domain\Message\AgentMessageNormalizer()), 100, $a);

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\ApplyCommandHandler'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\ApplyCommandHandler'];
        }

        return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\ApplyCommandHandler'] = $instance;
    }
}
