<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssistantThinkingStreamSubscriberService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Runtime\Stream\AssistantThinkingStreamSubscriber' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Runtime\Stream\AssistantThinkingStreamSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\CodingAgent\\Runtime\\Stream\\AssistantThinkingStreamSubscriber'] = new \Ineersa\CodingAgent\Runtime\Stream\AssistantThinkingStreamSubscriber(($container->privates['Ineersa\\CodingAgent\\Runtime\\InProcess\\InMemoryRuntimeEventSink'] ??= new \Ineersa\CodingAgent\Runtime\InProcess\InMemoryRuntimeEventSink()), ($container->privates['Ineersa\\CodingAgent\\Runtime\\Stream\\StdoutRuntimeEventSink'] ??= new \Ineersa\CodingAgent\Runtime\Stream\StdoutRuntimeEventSink()));
    }
}
