<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBashToolService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Tool\BashTool' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Tool\BashTool
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcessManager'] ?? $container->load('getBackgroundProcessManagerService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\BashTool'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\BashTool'];
        }
        $b = ($container->privates['Ineersa\\CodingAgent\\Tool\\OutputCap'] ?? $container->load('getOutputCapService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\BashTool'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\BashTool'];
        }
        $c = ($container->privates['Ineersa\\CodingAgent\\Config\\AppConfig'] ?? self::getAppConfigService($container));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\BashTool'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\BashTool'];
        }
        $d = ($container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\ToolQuestionStore'] ?? $container->load('getToolQuestionStoreService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\BashTool'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\BashTool'];
        }
        $e = ($container->privates['Ineersa\\AgentCore\\Application\\Tool\\StackToolExecutionContextAccessor'] ??= new \Ineersa\AgentCore\Application\Tool\StackToolExecutionContextAccessor());
        $f = ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'));

        $instance = new \Ineersa\CodingAgent\Tool\BashTool($a, $e, ($container->privates['Ineersa\\CodingAgent\\Tool\\ToolRuntime'] ?? $container->load('getToolRuntimeService')), $b, $f, \Ineersa\CodingAgent\Config\BashToolConfig::fromAppConfig($c), new \Ineersa\CodingAgent\Tool\ToolQuestion\RuntimeBashBackgroundPromptAdapter($e, $d, $f, new \Ineersa\CodingAgent\Tool\ToolQuestion\BackgroundProcessStatusChecker($a)));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\BashTool'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\BashTool'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Tool\\BashTool'] = $instance;
    }
}
