<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCodexAuthStorageService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Auth\CodexAuthStorage' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Auth\CodexAuthStorage
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['lock.default.factory'] ?? $container->load('getLock_Default_FactoryService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Auth\\CodexAuthStorage'])) {
            return $container->privates['Ineersa\\CodingAgent\\Auth\\CodexAuthStorage'];
        }

        $instance = new \Ineersa\CodingAgent\Auth\CodexAuthStorage(($container->privates['Ineersa\\CodingAgent\\Config\\SettingsPathResolver'] ??= new \Ineersa\CodingAgent\Config\SettingsPathResolver('phar:///home/ineersa/projects/agent-core-worktrees/maint-01-test-suite-maintenance-isolation-cleanup-flaky-gates/var/tmp/phar/hatfield.phar'))->getHomeDir(), $a, ($container->privates['Ineersa\\CodingAgent\\Auth\\CodexTokenRefresher'] ??= new \Ineersa\CodingAgent\Auth\CodexTokenRefresher()), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        if (isset($container->privates['Ineersa\\CodingAgent\\Auth\\CodexAuthStorage'])) {
            return $container->privates['Ineersa\\CodingAgent\\Auth\\CodexAuthStorage'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Auth\\CodexAuthStorage'] = $instance;
    }
}
