<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExtensionLoaderSubscriberService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Extension\ExtensionLoaderSubscriber' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Extension\ExtensionLoaderSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Config\\AppConfig'] ?? self::getAppConfigService($container));

        if (isset($container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionLoaderSubscriber'])) {
            return $container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionLoaderSubscriber'];
        }
        $b = ($container->privates['Ineersa\\CodingAgent\\Tool\\ToolRegistry'] ?? $container->load('getToolRegistryService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionLoaderSubscriber'])) {
            return $container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionLoaderSubscriber'];
        }
        $c = ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'));

        $instance = new \Ineersa\CodingAgent\Extension\ExtensionLoaderSubscriber(new \Ineersa\CodingAgent\Extension\ExtensionManager($a, new \Ineersa\CodingAgent\Extension\ExtensionToolRegistryBridge($b, ($container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionHookRegistry'] ??= new \Ineersa\CodingAgent\Extension\ExtensionHookRegistry()), $a), $c), $c);

        if (isset($container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionLoaderSubscriber'])) {
            return $container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionLoaderSubscriber'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionLoaderSubscriber'] = $instance;
    }
}
