<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHatfieldSessionRepositoryService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Entity\HatfieldSessionRepository' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Entity\HatfieldSessionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\CodingAgent\\Entity\\HatfieldSessionRepository'] = new \Ineersa\CodingAgent\Entity\HatfieldSessionRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
