<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLock_Default_FactoryService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'lock.default.factory' shared service.
     *
     * @return \Symfony\Component\Lock\LockFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\Lock\LockFactory(($container->privates['.lock.flock.store'] ?? $container->load('get_Lock_Flock_StoreService')));

        if (isset($container->privates['lock.default.factory'])) {
            return $container->privates['lock.default.factory'];
        }

        $container->privates['lock.default.factory'] = $instance;

        $a = new \Monolog\Logger('lock');
        $a->pushHandler(($container->privates['Ineersa\\CodingAgent\\Logging\\HatfieldRotatingLogHandler'] ?? self::getHatfieldRotatingLogHandlerService($container)));
        $a->pushProcessor(($container->privates['Ineersa\\CodingAgent\\Logging\\LogContextProcessor'] ??= new \Ineersa\CodingAgent\Logging\LogContextProcessor()));

        $instance->setLogger($a);

        return $instance;
    }
}
