<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogTailCommand_Command_LazyService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private '.Ineersa\CodingAgent\CLI\Log\LogTailCommand.command.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.Ineersa\\CodingAgent\\CLI\\Log\\LogTailCommand.command.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('log:tail', [], 'Show recent log entries', false, #[\Closure(name: 'Ineersa\\CodingAgent\\CLI\\Log\\LogTailCommand.command', class: 'Symfony\\Component\\Console\\Command\\Command')] fn (): \Symfony\Component\Console\Command\Command => ($container->privates['Ineersa\\CodingAgent\\CLI\\Log\\LogTailCommand.command'] ?? $container->load('getLogTailCommand_CommandService')));
    }
}
