<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Transport_SchedulerDefaultService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'messenger.transport.scheduler_default' shared service.
     *
     * @return \Symfony\Component\Messenger\Transport\TransportInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['messenger.transport_factory'] ?? $container->load('getMessenger_TransportFactoryService'));

        if (isset($container->privates['messenger.transport.scheduler_default'])) {
            return $container->privates['messenger.transport.scheduler_default'];
        }

        $instance = $a->createTransport('schedule://default', ['transport_name' => 'scheduler_default'], ($container->privates['.signing.messenger.default_serializer'] ?? $container->load('get_Signing_Messenger_DefaultSerializerService')));

        if (isset($container->privates['messenger.transport.scheduler_default'])) {
            return $container->privates['messenger.transport.scheduler_default'];
        }

        return $container->privates['messenger.transport.scheduler_default'] = $instance;
    }
}
