<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonolog_Logger_MessengerService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'monolog.logger.messenger' shared service.
     *
     * @return \Monolog\Logger
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Monolog\Logger('messenger');

        if (isset($container->privates['monolog.logger.messenger'])) {
            return $container->privates['monolog.logger.messenger'];
        }

        $container->privates['monolog.logger.messenger'] = $instance;

        $instance->pushHandler(($container->privates['Ineersa\\CodingAgent\\Logging\\HatfieldRotatingLogHandler'] ?? self::getHatfieldRotatingLogHandlerService($container)));
        $instance->pushProcessor(($container->privates['Ineersa\\CodingAgent\\Logging\\LogContextProcessor'] ??= new \Ineersa\CodingAgent\Logging\LogContextProcessor()));

        return $instance;
    }
}
