<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRuntimeEventMapperService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Runtime\Protocol\RuntimeEventMapper' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Runtime\Protocol\RuntimeEventMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['Ineersa\\CodingAgent\\Runtime\\Protocol\\RuntimeEventMapper'])) {
            return $container->privates['Ineersa\\CodingAgent\\Runtime\\Protocol\\RuntimeEventMapper'];
        }

        $instance = new \Ineersa\CodingAgent\Runtime\Protocol\RuntimeEventMapper(new \Ineersa\CodingAgent\Runtime\Protocol\RuntimeEventTranslator($a));

        if (isset($container->privates['Ineersa\\CodingAgent\\Runtime\\Protocol\\RuntimeEventMapper'])) {
            return $container->privates['Ineersa\\CodingAgent\\Runtime\\Protocol\\RuntimeEventMapper'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Runtime\\Protocol\\RuntimeEventMapper'] = $instance;
    }
}
