<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResumeHandlerService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Runtime\Controller\CommandHandler\ResumeHandler' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Runtime\Controller\CommandHandler\ResumeHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Runtime\\InProcess\\InProcessAgentSessionClient'] ?? $container->load('getInProcessAgentSessionClientService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Runtime\\Controller\\CommandHandler\\ResumeHandler'])) {
            return $container->privates['Ineersa\\CodingAgent\\Runtime\\Controller\\CommandHandler\\ResumeHandler'];
        }

        $instance = new \Ineersa\CodingAgent\Runtime\Controller\CommandHandler\ResumeHandler($a);

        if (isset($container->privates['Ineersa\\CodingAgent\\Runtime\\Controller\\CommandHandler\\ResumeHandler'])) {
            return $container->privates['Ineersa\\CodingAgent\\Runtime\\Controller\\CommandHandler\\ResumeHandler'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Runtime\\Controller\\CommandHandler\\ResumeHandler'] = $instance;
    }
}
