<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubmitListenerService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\Tui\Listener\SubmitListener' shared autowired service.
     *
     * @return \Ineersa\Tui\Listener\SubmitListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\Tui\\Listener\\SubmitListener'] = new \Ineersa\Tui\Listener\SubmitListener(($container->privates['Ineersa\\CodingAgent\\Session\\HatfieldSessionStore'] ?? $container->load('getHatfieldSessionStoreService')), new \Ineersa\Tui\Command\SubmissionRouter(new \Ineersa\Tui\Command\CommandParser(), ($container->privates['Ineersa\\Tui\\Command\\SlashCommandRegistry'] ??= new \Ineersa\Tui\Command\SlashCommandRegistry())), ($container->privates['Ineersa\\Tui\\Transcript\\TranscriptBlockFactory'] ??= new \Ineersa\Tui\Transcript\TranscriptBlockFactory()), ($container->privates['Ineersa\\Tui\\Question\\QuestionCoordinator'] ??= new \Ineersa\Tui\Question\QuestionCoordinator()), ($container->privates['Ineersa\\Tui\\Question\\QuestionController'] ?? $container->load('getQuestionControllerService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
