<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionCommandRegistrarService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\Tui\Listener\SessionCommandRegistrar' shared autowired service.
     *
     * @return \Ineersa\Tui\Listener\SessionCommandRegistrar
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\Tui\\Listener\\SessionCommandRegistrar'] = new \Ineersa\Tui\Listener\SessionCommandRegistrar(($container->privates['Ineersa\\Tui\\Command\\SlashCommandRegistry'] ??= new \Ineersa\Tui\Command\SlashCommandRegistry()), new \Ineersa\Tui\Picker\SessionPickerController(($container->privates['Ineersa\\CodingAgent\\Session\\HatfieldSessionStore'] ?? $container->load('getHatfieldSessionStoreService')), ($container->privates['Ineersa\\Tui\\Application\\TuiSessionSwitchService'] ?? $container->load('getTuiSessionSwitchServiceService'))));
    }
}
