<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSerializeControllerResultListenerService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'serialize_controller_result_listener' shared service.
     *
     * @return \Symfony\Component\HttpKernel\EventListener\SerializeControllerResultAttributeListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['serializer'] ?? self::getSerializerService($container));

        if (isset($container->privates['serialize_controller_result_listener'])) {
            return $container->privates['serialize_controller_result_listener'];
        }

        $instance = new \Symfony\Component\HttpKernel\EventListener\SerializeControllerResultAttributeListener($a);

        if (isset($container->privates['serialize_controller_result_listener'])) {
            return $container->privates['serialize_controller_result_listener'];
        }

        return $container->privates['serialize_controller_result_listener'] = $instance;
    }
}
