<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTranscriptProjectorService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Runtime\ProjectionPipeline\TranscriptProjector' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Runtime\ProjectionPipeline\TranscriptProjector
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\CodingAgent\\Runtime\\ProjectionPipeline\\TranscriptProjector'] = new \Ineersa\CodingAgent\Runtime\ProjectionPipeline\TranscriptProjector(($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), new \Ineersa\CodingAgent\Runtime\Projection\TranscriptProjectionState());
    }
}
