<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Lock_Flock_StoreService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private '.lock.flock.store' shared service.
     *
     * @return \Symfony\Component\Lock\Store\FlockStore
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/lock/PersistingStoreInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/lock/BlockingStoreInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/lock/SharedLockStoreInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/lock/Store/FlockStore.php';

        return $container->privates['.lock.flock.store'] = new \Symfony\Component\Lock\Store\FlockStore(\implode('/', [\sys_get_temp_dir(), 'symfony-lock', \hash('xxh64', \dirname(__DIR__, 4))]));
    }
}
