<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_ARP4CivService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.ARP4Civ' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';

        $a = ($container->privates['messenger.redispatch_message_handler'] ?? $container->load('getMessenger_RedispatchMessageHandlerService'));

        if (isset($container->privates['.messenger.handler_descriptor.ARP4Civ'])) {
            return $container->privates['.messenger.handler_descriptor.ARP4Civ'];
        }

        $instance = new \Symfony\Component\Messenger\Handler\HandlerDescriptor($a, []);

        if (isset($container->privates['.messenger.handler_descriptor.ARP4Civ'])) {
            return $container->privates['.messenger.handler_descriptor.ARP4Civ'];
        }

        return $container->privates['.messenger.handler_descriptor.ARP4Civ'] = $instance;
    }
}
