<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationMigrationExecutorService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Migrations\ApplicationMigrationExecutor' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Migrations\ApplicationMigrationExecutor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Migrations/ApplicationMigrationExecutor.php';

        return $container->privates['Ineersa\\CodingAgent\\Migrations\\ApplicationMigrationExecutor'] = new \Ineersa\CodingAgent\Migrations\ApplicationMigrationExecutor(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
