<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgentsContextDiscoveryService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\SystemPrompt\AgentsContextDiscovery' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\SystemPrompt\AgentsContextDiscovery
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/SystemPrompt/AgentsContextDiscovery.php';

        $a = ($container->privates['Ineersa\\CodingAgent\\Config\\AppConfig'] ?? self::getAppConfigService($container));

        if (isset($container->privates['Ineersa\\CodingAgent\\SystemPrompt\\AgentsContextDiscovery'])) {
            return $container->privates['Ineersa\\CodingAgent\\SystemPrompt\\AgentsContextDiscovery'];
        }

        $instance = new \Ineersa\CodingAgent\SystemPrompt\AgentsContextDiscovery(($container->privates['Ineersa\\CodingAgent\\Config\\SettingsPathResolver'] ??= new \Ineersa\CodingAgent\Config\SettingsPathResolver(\dirname(__DIR__, 4))), $a, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        if (isset($container->privates['Ineersa\\CodingAgent\\SystemPrompt\\AgentsContextDiscovery'])) {
            return $container->privates['Ineersa\\CodingAgent\\SystemPrompt\\AgentsContextDiscovery'];
        }

        return $container->privates['Ineersa\\CodingAgent\\SystemPrompt\\AgentsContextDiscovery'] = $instance;
    }
}
