<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCodingAgentImageCapabilityCheckerService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Tool\ImageProcessing\CodingAgentImageCapabilityChecker' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Tool\ImageProcessing\CodingAgentImageCapabilityChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Contract/Model/ImageCapabilityCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Tool/ImageProcessing/CodingAgentImageCapabilityChecker.php';

        $a = ($container->privates['Ineersa\\CodingAgent\\Config\\AppConfig'] ?? self::getAppConfigService($container));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\ImageProcessing\\CodingAgentImageCapabilityChecker'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\ImageProcessing\\CodingAgentImageCapabilityChecker'];
        }

        $instance = \Ineersa\CodingAgent\Tool\ImageProcessing\CodingAgentImageCapabilityChecker::fromAppConfig($a);

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\ImageProcessing\\CodingAgentImageCapabilityChecker'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\ImageProcessing\\CodingAgentImageCapabilityChecker'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Tool\\ImageProcessing\\CodingAgentImageCapabilityChecker'] = $instance;
    }
}
