<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHookDispatcherService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\AgentCore\Application\Handler\HookDispatcher' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Handler\HookDispatcher
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Handler/HookDispatcher.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Handler\\HookDispatcher'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\HookDispatcher'];
        }
        $b = ($container->privates['serializer'] ?? self::getSerializerService($container));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Handler\\HookDispatcher'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\HookDispatcher'];
        }

        $instance = new \Ineersa\AgentCore\Application\Handler\HookDispatcher(($container->privates['Ineersa\\AgentCore\\Application\\Handler\\HookSubscriberRegistry'] ?? $container->load('getHookSubscriberRegistryService')), $a, $b, $b);

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Handler\\HookDispatcher'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\HookDispatcher'];
        }

        return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\HookDispatcher'] = $instance;
    }
}
