<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLlmStepResultHandlerService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\AgentCore\Application\Pipeline\LlmStepResultHandler' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Pipeline\LlmStepResultHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Pipeline/RunMessageHandler.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Pipeline/LlmStepResultHandler.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Domain/Event/EventFactory.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Pipeline/ToolCallExtractor.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Domain/Message/AgentMessageNormalizer.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Handler/RunMetrics.php';

        $a = ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\ToolBatchCollector'] ?? $container->load('getToolBatchCollectorService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\LlmStepResultHandler'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\LlmStepResultHandler'];
        }
        $b = ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\StepDispatcher'] ?? $container->load('getStepDispatcherService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\LlmStepResultHandler'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\LlmStepResultHandler'];
        }
        $c = ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\LlmStepResultHandler'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\LlmStepResultHandler'];
        }

        $instance = new \Ineersa\AgentCore\Application\Pipeline\LlmStepResultHandler($a, ($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\CommandMailboxPolicy'] ?? $container->load('getCommandMailboxPolicyService')), ($container->privates['Ineersa\\AgentCore\\Domain\\Event\\EventFactory'] ??= new \Ineersa\AgentCore\Domain\Event\EventFactory()), ($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\ToolCallExtractor'] ??= new \Ineersa\AgentCore\Application\Pipeline\ToolCallExtractor()), ($container->privates['Ineersa\\AgentCore\\Domain\\Message\\AgentMessageNormalizer'] ??= new \Ineersa\AgentCore\Domain\Message\AgentMessageNormalizer()), $b, ($container->privates['Ineersa\\CodingAgent\\Tool\\CodingAgentToolSetResolver'] ?? $container->load('getCodingAgentToolSetResolverService')), ($container->privates['Ineersa\\CodingAgent\\Tool\\RegistryBackedToolbox'] ?? $container->load('getRegistryBackedToolboxService')), ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunMetrics'] ??= new \Ineersa\AgentCore\Application\Handler\RunMetrics()), ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunTracer'] ?? $container->load('getRunTracerService')), $c);

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\LlmStepResultHandler'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\LlmStepResultHandler'];
        }

        return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\LlmStepResultHandler'] = $instance;
    }
}
