<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogClearCommand_Command_LazyService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private '.Ineersa\CodingAgent\CLI\Log\LogClearCommand.command.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Ineersa\\CodingAgent\\CLI\\Log\\LogClearCommand.command.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('log:clear', [], 'Remove old rotated log files', false, #[\Closure(name: 'Ineersa\\CodingAgent\\CLI\\Log\\LogClearCommand.command', class: 'Symfony\\Component\\Console\\Command\\Command')] fn (): \Symfony\Component\Console\Command\Command => ($container->privates['Ineersa\\CodingAgent\\CLI\\Log\\LogClearCommand.command'] ?? $container->load('getLogClearCommand_CommandService')));
    }
}
