<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubmissionRouterService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\Tui\Command\SubmissionRouter' shared autowired service.
     *
     * @return \Ineersa\Tui\Command\SubmissionRouter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Tui/Command/SubmissionRouter.php';
        include_once \dirname(__DIR__, 4).'/src/Tui/Command/CommandParser.php';
        include_once \dirname(__DIR__, 4).'/src/Tui/Command/SlashCommandRegistry.php';

        return $container->privates['Ineersa\\Tui\\Command\\SubmissionRouter'] = new \Ineersa\Tui\Command\SubmissionRouter(($container->privates['Ineersa\\Tui\\Command\\CommandParser'] ??= new \Ineersa\Tui\Command\CommandParser()), ($container->privates['Ineersa\\Tui\\Command\\SlashCommandRegistry'] ??= new \Ineersa\Tui\Command\SlashCommandRegistry()));
    }
}
