<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToolRuntimeService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Tool\ToolRuntime' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Tool\ToolRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Tool/ToolRuntime.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Tool/StackToolExecutionContextAccessor.php';

        return $container->privates['Ineersa\\CodingAgent\\Tool\\ToolRuntime'] = new \Ineersa\CodingAgent\Tool\ToolRuntime(($container->privates['Ineersa\\AgentCore\\Application\\Tool\\StackToolExecutionContextAccessor'] ??= new \Ineersa\AgentCore\Application\Tool\StackToolExecutionContextAccessor()));
    }
}
