<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToolQuestionStoreService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Tool\ToolQuestion\ToolQuestionStore' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Tool\ToolQuestion\ToolQuestionStore
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Tool/ToolQuestion/ToolQuestionStoreInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Tool/ToolQuestion/ToolQuestionStore.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\ToolQuestionStore'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\ToolQuestionStore'];
        }

        $instance = new \Ineersa\CodingAgent\Tool\ToolQuestion\ToolQuestionStore($a, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\ToolQuestionStore'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\ToolQuestionStore'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\ToolQuestionStore'] = $instance;
    }
}
