<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getValidator_NotCompromisedPasswordService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'validator.not_compromised_password' shared service.
     *
     * @return \Symfony\Component\Validator\Constraints\NotCompromisedPasswordValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/Constraints/NotCompromisedPasswordValidator.php';

        $a = ($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService'));

        if (isset($container->privates['validator.not_compromised_password'])) {
            return $container->privates['validator.not_compromised_password'];
        }

        $instance = new \Symfony\Component\Validator\Constraints\NotCompromisedPasswordValidator($a, 'UTF-8', true, NULL);

        if (isset($container->privates['validator.not_compromised_password'])) {
            return $container->privates['validator.not_compromised_password'];
        }

        return $container->privates['validator.not_compromised_password'] = $instance;
    }
}
