<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgent_Execution_Bus_Middleware_HandleMessageService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'agent.execution.bus.middleware.handle_message' shared service.
     *
     * @return \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['agent.execution.bus.messenger.handlers_locator'] ?? $container->load('getAgent_Execution_Bus_Messenger_HandlersLocatorService'));

        if (isset($container->privates['agent.execution.bus.middleware.handle_message'])) {
            return $container->privates['agent.execution.bus.middleware.handle_message'];
        }

        $instance = new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware($a, false, ($container->privates['clock'] ??= new \Symfony\Component\Clock\Clock()), false);

        if (isset($container->privates['agent.execution.bus.middleware.handle_message'])) {
            return $container->privates['agent.execution.bus.middleware.handle_message'];
        }

        $container->privates['agent.execution.bus.middleware.handle_message'] = $instance;

        $instance->setLogger(($container->privates['monolog.logger.messenger'] ?? $container->load('getMonolog_Logger_MessengerService')));

        return $instance;
    }
}
