<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompatRequestShaperService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Config\CompatRequestShaper' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Config\CompatRequestShaper
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\CodingAgent\\Config\\CompatRequestShaper'] = new \Ineersa\CodingAgent\Config\CompatRequestShaper(($container->privates['Ineersa\\CodingAgent\\Config\\Ai\\HatfieldModelCatalog'] ?? $container->load('getHatfieldModelCatalogService')));
    }
}
