<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDynamicToolDescriptionProcessorService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\AgentCore\Infrastructure\SymfonyAi\DynamicToolDescriptionProcessor' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Infrastructure\SymfonyAi\DynamicToolDescriptionProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Tool\\RegistryBackedToolbox'] ?? $container->load('getRegistryBackedToolboxService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\DynamicToolDescriptionProcessor'])) {
            return $container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\DynamicToolDescriptionProcessor'];
        }
        $b = ($container->privates['Ineersa\\CodingAgent\\Tool\\CodingAgentToolSetResolver'] ?? $container->load('getCodingAgentToolSetResolverService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\DynamicToolDescriptionProcessor'])) {
            return $container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\DynamicToolDescriptionProcessor'];
        }

        $instance = new \Ineersa\AgentCore\Infrastructure\SymfonyAi\DynamicToolDescriptionProcessor($a, $b);

        if (isset($container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\DynamicToolDescriptionProcessor'])) {
            return $container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\DynamicToolDescriptionProcessor'];
        }

        return $container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\DynamicToolDescriptionProcessor'] = $instance;
    }
}
