<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileMentionCompletionProviderService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\Tui\Completion\FileMentionCompletionProvider' shared autowired service.
     *
     * @return \Ineersa\Tui\Completion\FileMentionCompletionProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\Tui\\Completion\\FileMentionCompletionProvider'] = new \Ineersa\Tui\Completion\FileMentionCompletionProvider(($container->privates['Ineersa\\Tui\\Completion\\FileMentionIndexReader'] ??= new \Ineersa\Tui\Completion\FileMentionIndexReader($container->getEnv('string:default:kernel.project_dir:string:HATFIELD_CWD').'/.hatfield/cache/file-mentions/index.jsonl')));
    }
}
