<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJsonlProcessAgentSessionClientService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Runtime\Process\JsonlProcessAgentSessionClient' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Runtime\Process\JsonlProcessAgentSessionClient
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\CodingAgent\\Runtime\\Process\\JsonlProcessAgentSessionClient'] = new \Ineersa\CodingAgent\Runtime\Process\JsonlProcessAgentSessionClient(($container->privates['Ineersa\\CodingAgent\\Runtime\\Process\\RuntimeProcessConfig'] ?? $container->load('getRuntimeProcessConfigService')));
    }
}
