<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogFilesCommand_CommandService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\CLI\Log\LogFilesCommand.command' shared service.
     *
     * @return \Symfony\Component\Console\Command\Command
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Ineersa\\CodingAgent\\CLI\\Log\\LogFilesCommand.command'] = $instance = new \Symfony\Component\Console\Command\Command();

        $instance->setCode(($container->privates['Ineersa\\CodingAgent\\CLI\\Log\\LogFilesCommand'] ?? $container->load('getLogFilesCommandService'))->__invoke(...));
        $instance->setName('log:files');
        $instance->setDescription('List log files with size and modification date');

        return $instance;
    }
}
