<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogFilesCommandService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\CLI\Log\LogFilesCommand' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\CLI\Log\LogFilesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\CodingAgent\\CLI\\Log\\LogFilesCommand'] = new \Ineersa\CodingAgent\CLI\Log\LogFilesCommand(($container->privates['Ineersa\\CodingAgent\\Logging\\LogReaderFactory'] ?? $container->load('getLogReaderFactoryService')));
    }
}
