<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Middleware_DeduplicateMiddlewareService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'messenger.middleware.deduplicate_middleware' shared service.
     *
     * @return \Symfony\Component\Messenger\Middleware\DeduplicateMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['lock.default.factory'] ?? $container->load('getLock_Default_FactoryService'));

        if (isset($container->privates['messenger.middleware.deduplicate_middleware'])) {
            return $container->privates['messenger.middleware.deduplicate_middleware'];
        }

        $instance = new \Symfony\Component\Messenger\Middleware\DeduplicateMiddleware($a);

        if (isset($container->privates['messenger.middleware.deduplicate_middleware'])) {
            return $container->privates['messenger.middleware.deduplicate_middleware'];
        }

        return $container->privates['messenger.middleware.deduplicate_middleware'] = $instance;
    }
}
