<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRuntimeBashBackgroundPromptAdapterService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Tool\ToolQuestion\RuntimeBashBackgroundPromptAdapter' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Tool\ToolQuestion\RuntimeBashBackgroundPromptAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\ToolQuestionStore'] ?? $container->load('getToolQuestionStoreService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\RuntimeBashBackgroundPromptAdapter'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\RuntimeBashBackgroundPromptAdapter'];
        }
        $b = ($container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\BackgroundProcessStatusChecker'] ?? $container->load('getBackgroundProcessStatusCheckerService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\RuntimeBashBackgroundPromptAdapter'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\RuntimeBashBackgroundPromptAdapter'];
        }

        $instance = new \Ineersa\CodingAgent\Tool\ToolQuestion\RuntimeBashBackgroundPromptAdapter(($container->privates['Ineersa\\AgentCore\\Application\\Tool\\StackToolExecutionContextAccessor'] ??= new \Ineersa\AgentCore\Application\Tool\StackToolExecutionContextAccessor()), $a, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), $b);

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\RuntimeBashBackgroundPromptAdapter'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\RuntimeBashBackgroundPromptAdapter'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\RuntimeBashBackgroundPromptAdapter'] = $instance;
    }
}
