<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRunMessageProcessorService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\AgentCore\Application\Pipeline\RunMessageProcessor' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Pipeline\RunMessageProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\MessageIdempotencyService'] ?? $container->load('getMessageIdempotencyServiceService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunMessageProcessor'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunMessageProcessor'];
        }
        $b = ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunLockManager'] ?? $container->load('getRunLockManagerService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunMessageProcessor'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunMessageProcessor'];
        }
        $c = ($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunCommit'] ?? $container->load('getRunCommitService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunMessageProcessor'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunMessageProcessor'];
        }
        $d = ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\StepDispatcher'] ?? $container->load('getStepDispatcherService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunMessageProcessor'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunMessageProcessor'];
        }
        $e = ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunStateReplayService'] ?? $container->load('getRunStateReplayServiceService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunMessageProcessor'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunMessageProcessor'];
        }

        $instance = new \Ineersa\AgentCore\Application\Pipeline\RunMessageProcessor(($container->privates['Ineersa\\CodingAgent\\Session\\SessionRunStore'] ?? $container->load('getSessionRunStoreService')), $a, $b, $c, $d, new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\AdvanceRunHandler'] ?? $container->load('getAdvanceRunHandlerService'));
            yield 1 => ($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\ApplyCommandHandler'] ?? $container->load('getApplyCommandHandlerService'));
            yield 2 => ($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\LlmStepResultHandler'] ?? $container->load('getLlmStepResultHandlerService'));
            yield 3 => ($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\StartRunHandler'] ?? $container->load('getStartRunHandlerService'));
            yield 4 => ($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\ToolCallResultHandler'] ?? $container->load('getToolCallResultHandlerService'));
        }, 5), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), $e);

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunMessageProcessor'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunMessageProcessor'];
        }

        return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunMessageProcessor'] = $instance;
    }
}
