<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRuntimeEventEmitterService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Runtime\Controller\RuntimeEventEmitter' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Runtime\Controller\RuntimeEventEmitter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\CodingAgent\\Runtime\\Controller\\RuntimeEventEmitter'] = new \Ineersa\CodingAgent\Runtime\Controller\RuntimeEventEmitter(($container->privates['Ineersa\\CodingAgent\\Runtime\\InProcess\\InProcessAgentSessionClient'] ?? $container->load('getInProcessAgentSessionClientService')), ($container->privates['Ineersa\\CodingAgent\\Runtime\\Contract\\RuntimeExceptionBoundary'] ?? $container->load('getRuntimeExceptionBoundaryService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
