<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScheduler_Messenger_ServiceCallMessageHandlerService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'scheduler.messenger.service_call_message_handler' shared service.
     *
     * @return \Symfony\Component\Scheduler\Messenger\ServiceCallMessageHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\Scheduler\Messenger\ServiceCallMessageHandler(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Ineersa\\CodingAgent\\CLI\\CompletionFileIndexRefreshCommand' => ['privates', 'Ineersa\\CodingAgent\\CLI\\CompletionFileIndexRefreshCommand', 'getCompletionFileIndexRefreshCommandService', true],
        ], [
            'Ineersa\\CodingAgent\\CLI\\CompletionFileIndexRefreshCommand' => 'Ineersa\\CodingAgent\\CLI\\CompletionFileIndexRefreshCommand',
        ]));

        if (isset($container->privates['scheduler.messenger.service_call_message_handler'])) {
            return $container->privates['scheduler.messenger.service_call_message_handler'];
        }

        return $container->privates['scheduler.messenger.service_call_message_handler'] = $instance;
    }
}
