<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_9JusjcHService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.9JusjcH' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';

        $a = ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\ExecuteToolCallWorker'] ?? $container->load('getExecuteToolCallWorkerService'));

        if (isset($container->privates['.messenger.handler_descriptor.9JusjcH'])) {
            return $container->privates['.messenger.handler_descriptor.9JusjcH'];
        }

        $instance = new \Symfony\Component\Messenger\Handler\HandlerDescriptor($a, ['bus' => 'agent.execution.bus', 'method' => '__invoke']);

        if (isset($container->privates['.messenger.handler_descriptor.9JusjcH'])) {
            return $container->privates['.messenger.handler_descriptor.9JusjcH'];
        }

        return $container->privates['.messenger.handler_descriptor.9JusjcH'] = $instance;
    }
}
