<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompletionProviderRegistryService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\Tui\Completion\CompletionProviderRegistry' shared autowired service.
     *
     * @return \Ineersa\Tui\Completion\CompletionProviderRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Tui/Completion/CompletionProvider.php';
        include_once \dirname(__DIR__, 4).'/src/Tui/Completion/CompletionProviderRegistry.php';

        return $container->privates['Ineersa\\Tui\\Completion\\CompletionProviderRegistry'] = new \Ineersa\Tui\Completion\CompletionProviderRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Ineersa\\Tui\\Completion\\SlashCommandCompletionProvider'] ?? $container->load('getSlashCommandCompletionProviderService'));
            yield 1 => ($container->privates['Ineersa\\Tui\\Completion\\FileMentionCompletionProvider'] ?? $container->load('getFileMentionCompletionProviderService'));
        }, 2));
    }
}
