<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageAttachmentProcessorService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Tool\ImageProcessing\ImageAttachmentProcessor' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Tool\ImageProcessing\ImageAttachmentProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Tool/ImageProcessing/ImageAttachmentProcessor.php';

        return $container->privates['Ineersa\\CodingAgent\\Tool\\ImageProcessing\\ImageAttachmentProcessor'] = new \Ineersa\CodingAgent\Tool\ImageProcessing\ImageAttachmentProcessor(($container->privates['Ineersa\\CodingAgent\\Config\\ImageToolConfig'] ?? $container->load('getImageToolConfigService')));
    }
}
