<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogReaderFactoryService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Logging\LogReaderFactory' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Logging\LogReaderFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Logging/LogReaderFactory.php';

        return $container->privates['Ineersa\\CodingAgent\\Logging\\LogReaderFactory'] = new \Ineersa\CodingAgent\Logging\LogReaderFactory(($container->privates['Ineersa\\CodingAgent\\Config\\LoggingConfig'] ?? self::getLoggingConfigService($container)));
    }
}
