<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModelResolverRoutingSubscriberService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\AgentCore\Infrastructure\SymfonyAi\ModelResolverRoutingSubscriber' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Infrastructure\SymfonyAi\ModelResolverRoutingSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Infrastructure/SymfonyAi/ModelResolverRoutingSubscriber.php';

        $a = ($container->privates['Ineersa\\CodingAgent\\Infrastructure\\SymfonyAi\\SymfonyAiProviderRegistry'] ?? $container->load('getSymfonyAiProviderRegistryService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\ModelResolverRoutingSubscriber'])) {
            return $container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\ModelResolverRoutingSubscriber'];
        }

        $instance = new \Ineersa\AgentCore\Infrastructure\SymfonyAi\ModelResolverRoutingSubscriber(($container->privates['Ineersa\\CodingAgent\\Config\\SessionAwareModelResolver'] ?? $container->load('getSessionAwareModelResolverService')), $a);

        if (isset($container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\ModelResolverRoutingSubscriber'])) {
            return $container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\ModelResolverRoutingSubscriber'];
        }

        return $container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\ModelResolverRoutingSubscriber'] = $instance;
    }
}
