<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSkillsConfigService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Skills\SkillsConfig' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Skills\SkillsConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Skills/SkillsConfig.php';

        return $container->privates['Ineersa\\CodingAgent\\Skills\\SkillsConfig'] = new \Ineersa\CodingAgent\Skills\SkillsConfig();
    }
}
