<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSystemPromptBuilderService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\SystemPrompt\SystemPromptBuilder' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\SystemPrompt\SystemPromptBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/SystemPrompt/SystemPromptBuilder.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ai-platform/src/Message/TemplateRenderer/TemplateRendererInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ai-platform/src/Message/TemplateRenderer/StringTemplateRenderer.php';

        $a = ($container->privates['Ineersa\\CodingAgent\\Tool\\ToolRegistry'] ?? $container->load('getToolRegistryService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\SystemPrompt\\SystemPromptBuilder'])) {
            return $container->privates['Ineersa\\CodingAgent\\SystemPrompt\\SystemPromptBuilder'];
        }
        $b = ($container->privates['Ineersa\\CodingAgent\\Config\\AppConfig'] ?? self::getAppConfigService($container));

        if (isset($container->privates['Ineersa\\CodingAgent\\SystemPrompt\\SystemPromptBuilder'])) {
            return $container->privates['Ineersa\\CodingAgent\\SystemPrompt\\SystemPromptBuilder'];
        }

        $instance = new \Ineersa\CodingAgent\SystemPrompt\SystemPromptBuilder($a, ($container->privates['Ineersa\\CodingAgent\\Config\\SettingsPathResolver'] ??= new \Ineersa\CodingAgent\Config\SettingsPathResolver(\dirname(__DIR__, 4))), ($container->privates['Symfony\\AI\\Platform\\Message\\TemplateRenderer\\StringTemplateRenderer'] ??= new \Symfony\AI\Platform\Message\TemplateRenderer\StringTemplateRenderer()), $b, \dirname(__DIR__, 4));

        if (isset($container->privates['Ineersa\\CodingAgent\\SystemPrompt\\SystemPromptBuilder'])) {
            return $container->privates['Ineersa\\CodingAgent\\SystemPrompt\\SystemPromptBuilder'];
        }

        return $container->privates['Ineersa\\CodingAgent\\SystemPrompt\\SystemPromptBuilder'] = $instance;
    }
}
