<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionCommandRegistrarService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\Tui\Listener\SessionCommandRegistrar' shared autowired service.
     *
     * @return \Ineersa\Tui\Listener\SessionCommandRegistrar
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Tui/Listener/TuiListenerRegistrar.php';
        include_once \dirname(__DIR__, 4).'/src/Tui/Listener/SessionCommandRegistrar.php';
        include_once \dirname(__DIR__, 4).'/src/Tui/Command/SlashCommandRegistry.php';

        return $container->privates['Ineersa\\Tui\\Listener\\SessionCommandRegistrar'] = new \Ineersa\Tui\Listener\SessionCommandRegistrar(($container->privates['Ineersa\\Tui\\Command\\SlashCommandRegistry'] ??= new \Ineersa\Tui\Command\SlashCommandRegistry()), ($container->privates['Ineersa\\Tui\\Picker\\SessionPickerController'] ?? $container->load('getSessionPickerControllerService')));
    }
}
