<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSymfonyAiProviderRegistryService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Infrastructure\SymfonyAi\SymfonyAiProviderRegistry' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Infrastructure\SymfonyAi\SymfonyAiProviderRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Contract/Model/ProviderRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Infrastructure/SymfonyAi/SymfonyAiProviderRegistry.php';

        $a = ($container->privates['Ineersa\\CodingAgent\\Infrastructure\\SymfonyAi\\SymfonyAiProviderFactory'] ?? $container->load('getSymfonyAiProviderFactoryService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Infrastructure\\SymfonyAi\\SymfonyAiProviderRegistry'])) {
            return $container->privates['Ineersa\\CodingAgent\\Infrastructure\\SymfonyAi\\SymfonyAiProviderRegistry'];
        }

        $instance = new \Ineersa\CodingAgent\Infrastructure\SymfonyAi\SymfonyAiProviderRegistry($a);

        if (isset($container->privates['Ineersa\\CodingAgent\\Infrastructure\\SymfonyAi\\SymfonyAiProviderRegistry'])) {
            return $container->privates['Ineersa\\CodingAgent\\Infrastructure\\SymfonyAi\\SymfonyAiProviderRegistry'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Infrastructure\\SymfonyAi\\SymfonyAiProviderRegistry'] = $instance;
    }
}
