<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToolExecutorService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\AgentCore\Application\Handler\ToolExecutor' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Handler\ToolExecutor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Contract/Tool/ToolExecutorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Handler/ToolExecutor.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Handler/ToolExecutionResultStore.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Tool/StackToolExecutionContextAccessor.php';

        $a = ($container->privates['Ineersa\\CodingAgent\\Config\\ToolSettings'] ?? $container->load('getToolSettingsService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Handler\\ToolExecutor'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\ToolExecutor'];
        }

        $instance = \Ineersa\AgentCore\Application\Handler\ToolExecutor::fromSettings($a, ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\ToolExecutionResultStore'] ??= new \Ineersa\AgentCore\Application\Handler\ToolExecutionResultStore()), ($container->privates['Ineersa\\CodingAgent\\Tool\\RegistryBackedToolbox'] ?? $container->load('getRegistryBackedToolboxService')), NULL, ($container->privates['Ineersa\\AgentCore\\Application\\Tool\\StackToolExecutionContextAccessor'] ??= new \Ineersa\AgentCore\Application\Tool\StackToolExecutionContextAccessor()), ($container->privates['Ineersa\\CodingAgent\\Tool\\CodingAgentToolSetResolver'] ?? $container->load('getCodingAgentToolSetResolverService')));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Handler\\ToolExecutor'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\ToolExecutor'];
        }

        return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\ToolExecutor'] = $instance;
    }
}
