<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTranscriptProjectorService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Runtime\ProjectionPipeline\TranscriptProjector' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Runtime\ProjectionPipeline\TranscriptProjector
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Runtime/Contract/TranscriptProjectorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Runtime/ProjectionPipeline/TranscriptProjector.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Runtime/Projection/TranscriptProjectionState.php';

        return $container->privates['Ineersa\\CodingAgent\\Runtime\\ProjectionPipeline\\TranscriptProjector'] = new \Ineersa\CodingAgent\Runtime\ProjectionPipeline\TranscriptProjector(($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), ($container->privates['Ineersa\\CodingAgent\\Runtime\\Projection\\TranscriptProjectionState'] ??= new \Ineersa\CodingAgent\Runtime\Projection\TranscriptProjectionState()));
    }
}
