<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getValidator_ExpressionService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'validator.expression' shared service.
     *
     * @return \Symfony\Component\Validator\Constraints\ExpressionValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/Constraints/ExpressionValidator.php';

        $a = ($container->privates['validator.expression_language'] ?? $container->load('getValidator_ExpressionLanguageService'));

        if (isset($container->privates['validator.expression'])) {
            return $container->privates['validator.expression'];
        }

        $instance = new \Symfony\Component\Validator\Constraints\ExpressionValidator($a);

        if (isset($container->privates['validator.expression'])) {
            return $container->privates['validator.expression'];
        }

        return $container->privates['validator.expression'] = $instance;
    }
}
