<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7D9yQRcService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private '.service_locator.7D9yQRc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'run_control' => ['privates', 'messenger.transport.run_control', 'getMessenger_Transport_RunControlService', true],
            'llm' => ['privates', 'messenger.transport.llm', 'getMessenger_Transport_LlmService', true],
            'tool' => ['privates', 'messenger.transport.tool', 'getMessenger_Transport_ToolService', true],
            'messenger.transport.run_control' => ['privates', 'messenger.transport.run_control', 'getMessenger_Transport_RunControlService', true],
            'messenger.transport.llm' => ['privates', 'messenger.transport.llm', 'getMessenger_Transport_LlmService', true],
            'messenger.transport.tool' => ['privates', 'messenger.transport.tool', 'getMessenger_Transport_ToolService', true],
        ], [
            'run_control' => '?',
            'llm' => '?',
            'tool' => '?',
            'messenger.transport.run_control' => '?',
            'messenger.transport.llm' => '?',
            'messenger.transport.tool' => '?',
        ]);

        if (isset($container->privates['.service_locator.7D9yQRc'])) {
            return $container->privates['.service_locator.7D9yQRc'];
        }

        return $container->privates['.service_locator.7D9yQRc'] = $instance;
    }
}
