<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDdtraceSpanProviderService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Logging\DdtraceSpanProvider' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Logging\DdtraceSpanProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\CodingAgent\\Logging\\DdtraceSpanProvider'] = new \Ineersa\CodingAgent\Logging\DdtraceSpanProvider();
    }
}
