<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExtensionLoaderSubscriberService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Extension\ExtensionLoaderSubscriber' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Extension\ExtensionLoaderSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionManager'] ?? $container->load('getExtensionManagerService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionLoaderSubscriber'])) {
            return $container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionLoaderSubscriber'];
        }

        $instance = new \Ineersa\CodingAgent\Extension\ExtensionLoaderSubscriber($a, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        if (isset($container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionLoaderSubscriber'])) {
            return $container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionLoaderSubscriber'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionLoaderSubscriber'] = $instance;
    }
}
