<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileMentionIndexBuilderService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\CLI\FileMentionIndexBuilder' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\CLI\FileMentionIndexBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['lock.default.factory'] ?? $container->load('getLock_Default_FactoryService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\CLI\\FileMentionIndexBuilder'])) {
            return $container->privates['Ineersa\\CodingAgent\\CLI\\FileMentionIndexBuilder'];
        }

        $instance = new \Ineersa\CodingAgent\CLI\FileMentionIndexBuilder($container->getEnv('default:kernel.project_dir:string:HATFIELD_CWD'), $container->getEnv('string:default:kernel.project_dir:string:HATFIELD_CWD').'/.hatfield/cache/file-mentions/index.jsonl', ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), $a);

        if (isset($container->privates['Ineersa\\CodingAgent\\CLI\\FileMentionIndexBuilder'])) {
            return $container->privates['Ineersa\\CodingAgent\\CLI\\FileMentionIndexBuilder'];
        }

        return $container->privates['Ineersa\\CodingAgent\\CLI\\FileMentionIndexBuilder'] = $instance;
    }
}
