<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogClearCommand_CommandService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\CLI\Log\LogClearCommand.command' shared service.
     *
     * @return \Symfony\Component\Console\Command\Command
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Ineersa\\CodingAgent\\CLI\\Log\\LogClearCommand.command'] = $instance = new \Symfony\Component\Console\Command\Command();

        $instance->setCode(($container->privates['Ineersa\\CodingAgent\\CLI\\Log\\LogClearCommand'] ?? $container->load('getLogClearCommandService'))->__invoke(...));
        $instance->setName('log:clear');
        $instance->setDescription('Remove old rotated log files');

        return $instance;
    }
}
