<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogFilesCommand_Command_LazyService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private '.Ineersa\CodingAgent\CLI\Log\LogFilesCommand.command.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.Ineersa\\CodingAgent\\CLI\\Log\\LogFilesCommand.command.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('log:files', [], 'List log files with size and modification date', false, #[\Closure(name: 'Ineersa\\CodingAgent\\CLI\\Log\\LogFilesCommand.command', class: 'Symfony\\Component\\Console\\Command\\Command')] fn (): \Symfony\Component\Console\Command\Command => ($container->privates['Ineersa\\CodingAgent\\CLI\\Log\\LogFilesCommand.command'] ?? $container->load('getLogFilesCommand_CommandService')));
    }
}
