<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLlmPlatformAdapterService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\AgentCore\Infrastructure\SymfonyAi\LlmPlatformAdapter' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Infrastructure\SymfonyAi\LlmPlatformAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\DynamicToolDescriptionProcessor'] ?? $container->load('getDynamicToolDescriptionProcessorService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\LlmPlatformAdapter'])) {
            return $container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\LlmPlatformAdapter'];
        }
        $b = ($container->privates['Symfony\\AI\\Platform\\PlatformInterface'] ?? $container->load('getPlatformInterfaceService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\LlmPlatformAdapter'])) {
            return $container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\LlmPlatformAdapter'];
        }
        $c = ($container->privates['Ineersa\\CodingAgent\\Runtime\\Stream\\LlmStreamDispatchObserver'] ?? $container->load('getLlmStreamDispatchObserverService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\LlmPlatformAdapter'])) {
            return $container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\LlmPlatformAdapter'];
        }

        $instance = new \Ineersa\AgentCore\Infrastructure\SymfonyAi\LlmPlatformAdapter(($container->privates['Ineersa\\CodingAgent\\Session\\SessionRunStore'] ?? $container->load('getSessionRunStoreService')), ($container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\AgentMessageConverter'] ??= new \Ineersa\AgentCore\Infrastructure\SymfonyAi\AgentMessageConverter()), $a, $b, new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Ineersa\\CodingAgent\\Tool\\OutputCapLlmTransformHook'] ?? $container->load('getOutputCapLlmTransformHookService'));
        }, 1), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Ineersa\\CodingAgent\\Tool\\ImageProcessing\\ImageGatingConvertHook'] ?? $container->load('getImageGatingConvertHookService'));
        }, 1), $c, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        if (isset($container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\LlmPlatformAdapter'])) {
            return $container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\LlmPlatformAdapter'];
        }

        return $container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\LlmPlatformAdapter'] = $instance;
    }
}
