<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatformInterfaceService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Symfony\AI\Platform\PlatformInterface' shared autowired service.
     *
     * @return \Symfony\AI\Platform\PlatformInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Infrastructure\\SymfonyAi\\ConfiguredSymfonyAiPlatformFactory'] ?? $container->load('getConfiguredSymfonyAiPlatformFactoryService'));

        if (isset($container->privates['Symfony\\AI\\Platform\\PlatformInterface'])) {
            return $container->privates['Symfony\\AI\\Platform\\PlatformInterface'];
        }

        $instance = $a->createPlatform();

        if (isset($container->privates['Symfony\\AI\\Platform\\PlatformInterface'])) {
            return $container->privates['Symfony\\AI\\Platform\\PlatformInterface'];
        }

        return $container->privates['Symfony\\AI\\Platform\\PlatformInterface'] = $instance;
    }
}
