<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRunCommitService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\AgentCore\Application\Pipeline\RunCommit' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Pipeline\RunCommit
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Session\\SessionRunEventStore'] ?? $container->load('getSessionRunEventStoreService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunCommit'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunCommit'];
        }
        $b = ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\ReplayService'] ?? $container->load('getReplayServiceService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunCommit'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunCommit'];
        }
        $c = ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\StepDispatcher'] ?? $container->load('getStepDispatcherService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunCommit'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunCommit'];
        }
        $d = ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\HookDispatcher'] ?? $container->load('getHookDispatcherService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunCommit'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunCommit'];
        }

        $instance = new \Ineersa\AgentCore\Application\Pipeline\RunCommit(($container->privates['Ineersa\\CodingAgent\\Session\\SessionRunStore'] ?? $container->load('getSessionRunStoreService')), $a, ($container->privates['Ineersa\\AgentCore\\Infrastructure\\Storage\\InMemoryCommandStore'] ??= new \Ineersa\AgentCore\Infrastructure\Storage\InMemoryCommandStore()), $b, $c, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), $d, ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunMetrics'] ??= new \Ineersa\AgentCore\Application\Handler\RunMetrics()), ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunTracer'] ?? $container->load('getRunTracerService')));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunCommit'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunCommit'];
        }

        return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\RunCommit'] = $instance;
    }
}
