<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionInitializerService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\Tui\Application\SessionInitializer' shared autowired service.
     *
     * @return \Ineersa\Tui\Application\SessionInitializer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\Tui\\Application\\SessionInitializer'] = new \Ineersa\Tui\Application\SessionInitializer(($container->privates['Ineersa\\CodingAgent\\Session\\HatfieldSessionStore'] ?? $container->load('getHatfieldSessionStoreService')), ($container->privates['Ineersa\\CodingAgent\\Session\\SessionRunEventStore'] ?? $container->load('getSessionRunEventStoreService')), ($container->privates['Ineersa\\CodingAgent\\Runtime\\Protocol\\RuntimeEventMapper'] ?? $container->load('getRuntimeEventMapperService')), ($container->privates['Ineersa\\CodingAgent\\Runtime\\ProjectionPipeline\\TranscriptProjector'] ?? $container->load('getTranscriptProjectorService')), ($container->privates['Ineersa\\Tui\\Transcript\\TranscriptBlockFactory'] ??= new \Ineersa\Tui\Transcript\TranscriptBlockFactory()), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
