<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToolBatchStateRepositoryService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Entity\ToolBatchStateRepository' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Entity\ToolBatchStateRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\CodingAgent\\Entity\\ToolBatchStateRepository'] = new \Ineersa\CodingAgent\Entity\ToolBatchStateRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
