<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToolCallResultHandlerService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\AgentCore\Application\Pipeline\ToolCallResultHandler' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Pipeline\ToolCallResultHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\ToolBatchCollector'] ?? $container->load('getToolBatchCollectorService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\ToolCallResultHandler'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\ToolCallResultHandler'];
        }
        $b = ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\ToolCallResultHandler'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\ToolCallResultHandler'];
        }

        $instance = new \Ineersa\AgentCore\Application\Pipeline\ToolCallResultHandler($a, ($container->privates['Ineersa\\AgentCore\\Domain\\Event\\EventFactory'] ??= new \Ineersa\AgentCore\Domain\Event\EventFactory()), ($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\ToolCallExtractor'] ??= new \Ineersa\AgentCore\Application\Pipeline\ToolCallExtractor()), ($container->privates['Ineersa\\AgentCore\\Domain\\Message\\AgentMessageNormalizer'] ??= new \Ineersa\AgentCore\Domain\Message\AgentMessageNormalizer()), ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunMetrics'] ??= new \Ineersa\AgentCore\Application\Handler\RunMetrics()), $b);

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\ToolCallResultHandler'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\ToolCallResultHandler'];
        }

        return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\ToolCallResultHandler'] = $instance;
    }
}
