<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWriteFileToolService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Tool\WriteFileTool' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Tool\WriteFileTool
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\CodingAgent\\Tool\\WriteFileTool'] = new \Ineersa\CodingAgent\Tool\WriteFileTool(($container->privates['Ineersa\\CodingAgent\\Tool\\ToolRuntime'] ?? $container->load('getToolRuntimeService')));
    }
}
