<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvanceRunHandlerService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\AgentCore\Application\Pipeline\AdvanceRunHandler' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Pipeline\AdvanceRunHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Pipeline/RunMessageHandler.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Pipeline/AdvanceRunHandler.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Domain/Event/EventFactory.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Handler/RunMetrics.php';

        return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\AdvanceRunHandler'] = new \Ineersa\AgentCore\Application\Pipeline\AdvanceRunHandler(($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\CommandMailboxPolicy'] ?? $container->load('getCommandMailboxPolicyService')), ($container->privates['Ineersa\\AgentCore\\Domain\\Event\\EventFactory'] ??= new \Ineersa\AgentCore\Domain\Event\EventFactory()), ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunMetrics'] ??= new \Ineersa\AgentCore\Application\Handler\RunMetrics()), ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunTracer'] ?? $container->load('getRunTracerService')));
    }
}
