<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBashToolConfigService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Config\BashToolConfig' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Config\BashToolConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Config/BashToolConfig.php';

        $a = ($container->privates['Ineersa\\CodingAgent\\Config\\AppConfig'] ?? self::getAppConfigService($container));

        if (isset($container->privates['Ineersa\\CodingAgent\\Config\\BashToolConfig'])) {
            return $container->privates['Ineersa\\CodingAgent\\Config\\BashToolConfig'];
        }

        $instance = \Ineersa\CodingAgent\Config\BashToolConfig::fromAppConfig($a);

        if (isset($container->privates['Ineersa\\CodingAgent\\Config\\BashToolConfig'])) {
            return $container->privates['Ineersa\\CodingAgent\\Config\\BashToolConfig'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Config\\BashToolConfig'] = $instance;
    }
}
