<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCodingAgentToolSetResolverService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Tool\CodingAgentToolSetResolver' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Tool\CodingAgentToolSetResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Contract/Tool/ToolSetResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Tool/CodingAgentToolSetResolver.php';

        $a = ($container->privates['Ineersa\\CodingAgent\\Tool\\ToolRegistry'] ?? $container->load('getToolRegistryService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\CodingAgentToolSetResolver'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\CodingAgentToolSetResolver'];
        }

        $instance = new \Ineersa\CodingAgent\Tool\CodingAgentToolSetResolver($a);

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\CodingAgentToolSetResolver'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\CodingAgentToolSetResolver'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Tool\\CodingAgentToolSetResolver'] = $instance;
    }
}
