<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCache_ValidatorExpressionLanguageService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'cache.validator_expression_language' shared service.
     *
     * @return \Symfony\Component\Cache\Adapter\AdapterInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['monolog.logger.cache'] ?? self::getMonolog_Logger_CacheService($container));

        if (isset($container->privates['cache.validator_expression_language'])) {
            return $container->privates['cache.validator_expression_language'];
        }

        $instance = \Symfony\Component\Cache\Adapter\AbstractAdapter::createSystemCache('Bj6g8FGpcX', 0, $container->getParameter('container.build_id'), ($container->targetDir.''.'/pools/system'), $a);

        if (isset($container->privates['cache.validator_expression_language'])) {
            return $container->privates['cache.validator_expression_language'];
        }

        return $container->privates['cache.validator_expression_language'] = $instance;
    }
}
