<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompletionFileIndexRefreshCommandService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\CLI\CompletionFileIndexRefreshCommand' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\CLI\CompletionFileIndexRefreshCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/CLI/CompletionFileIndexRefreshCommand.php';

        $a = ($container->privates['Ineersa\\CodingAgent\\CLI\\FileMentionIndexBuilder'] ?? $container->load('getFileMentionIndexBuilderService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\CLI\\CompletionFileIndexRefreshCommand'])) {
            return $container->privates['Ineersa\\CodingAgent\\CLI\\CompletionFileIndexRefreshCommand'];
        }

        $instance = new \Ineersa\CodingAgent\CLI\CompletionFileIndexRefreshCommand($a, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        if (isset($container->privates['Ineersa\\CodingAgent\\CLI\\CompletionFileIndexRefreshCommand'])) {
            return $container->privates['Ineersa\\CodingAgent\\CLI\\CompletionFileIndexRefreshCommand'];
        }

        $container->privates['Ineersa\\CodingAgent\\CLI\\CompletionFileIndexRefreshCommand'] = $instance;

        $instance->setName('completion:file-index:refresh');
        $instance->setDescription('Rebuild the file mention completion index for the current project.');

        return $instance;
    }
}
