<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExtensionToolHookEventSubscriberService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Extension\ExtensionToolHookEventSubscriber' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Extension\ExtensionToolHookEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Extension/ExtensionToolHookEventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Extension/ExtensionHookRegistry.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Tool/StackToolExecutionContextAccessor.php';

        $instance = new \Ineersa\CodingAgent\Extension\ExtensionToolHookEventSubscriber(($container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionHookRegistry'] ??= new \Ineersa\CodingAgent\Extension\ExtensionHookRegistry()), ($container->privates['Ineersa\\CodingAgent\\Config\\AppConfig'] ?? self::getAppConfigService($container))->cwd, ($container->privates['Ineersa\\AgentCore\\Application\\Tool\\StackToolExecutionContextAccessor'] ??= new \Ineersa\AgentCore\Application\Tool\StackToolExecutionContextAccessor()));

        if (isset($container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionToolHookEventSubscriber'])) {
            return $container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionToolHookEventSubscriber'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionToolHookEventSubscriber'] = $instance;
    }
}
