<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFooterStateListenerService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\Tui\Listener\FooterStateListener' shared autowired service.
     *
     * @return \Ineersa\Tui\Listener\FooterStateListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Tui/Listener/TuiListenerRegistrar.php';
        include_once \dirname(__DIR__, 4).'/src/Tui/Listener/FooterStateListener.php';

        return $container->privates['Ineersa\\Tui\\Listener\\FooterStateListener'] = new \Ineersa\Tui\Listener\FooterStateListener(($container->privates['Ineersa\\Tui\\Listener\\FooterStateInitializer'] ?? $container->load('getFooterStateInitializerService')));
    }
}
