<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHttpClient_TransportService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'http_client.transport' shared service.
     *
     * @return \Symfony\Contracts\HttpClient\HttpClientInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-client-contracts/HttpClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-client/HttpClient.php';

        $instance = \Symfony\Component\HttpClient\HttpClient::create([], 6);

        if (isset($container->privates['http_client.transport'])) {
            return $container->privates['http_client.transport'];
        }

        $container->privates['http_client.transport'] = $instance;

        $instance->setLogger(($container->privates['monolog.logger.http_client'] ?? $container->load('getMonolog_Logger_HttpClientService')));

        return $instance;
    }
}
