<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHttpClient_UriTemplate_InnerService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'http_client.uri_template.inner' shared service.
     *
     * @return \Symfony\Contracts\HttpClient\HttpClientInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-client-contracts/HttpClientInterface.php';

        $a = ($container->privates['http_client.transport'] ?? $container->load('getHttpClient_TransportService'));

        if (isset($container->privates['http_client.uri_template.inner'])) {
            return $container->privates['http_client.uri_template.inner'];
        }

        $instance = $a;

        if (isset($container->privates['http_client.uri_template.inner'])) {
            return $container->privates['http_client.uri_template.inner'];
        }

        return $container->privates['http_client.uri_template.inner'] = $instance;
    }
}
