<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInMemoryRuntimeEventSinkService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Runtime\InProcess\InMemoryRuntimeEventSink' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Runtime\InProcess\InMemoryRuntimeEventSink
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Runtime/Contract/RuntimeEventSinkInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Runtime/InProcess/InMemoryRuntimeEventSink.php';

        return $container->privates['Ineersa\\CodingAgent\\Runtime\\InProcess\\InMemoryRuntimeEventSink'] = new \Ineersa\CodingAgent\Runtime\InProcess\InMemoryRuntimeEventSink();
    }
}
