<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogTailCommand_CommandService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\CLI\Log\LogTailCommand.command' shared service.
     *
     * @return \Symfony\Component\Console\Command\Command
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';

        $container->privates['Ineersa\\CodingAgent\\CLI\\Log\\LogTailCommand.command'] = $instance = new \Symfony\Component\Console\Command\Command();

        $instance->setCode(($container->privates['Ineersa\\CodingAgent\\CLI\\Log\\LogTailCommand'] ?? $container->load('getLogTailCommandService'))->__invoke(...));
        $instance->setName('log:tail');
        $instance->setDescription('Show recent log entries');

        return $instance;
    }
}
