<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModelPickerControllerService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\Tui\Picker\ModelPickerController' shared autowired service.
     *
     * @return \Ineersa\Tui\Picker\ModelPickerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Tui/Picker/ModelPickerController.php';

        return $container->privates['Ineersa\\Tui\\Picker\\ModelPickerController'] = new \Ineersa\Tui\Picker\ModelPickerController(($container->privates['Ineersa\\CodingAgent\\Config\\ModelSelectionService'] ?? $container->load('getModelSelectionServiceService')), ($container->privates['Ineersa\\CodingAgent\\Config\\AppConfig'] ?? self::getAppConfigService($container)), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
