<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTuiSessionSwitchServiceService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\Tui\Application\TuiSessionSwitchService' shared autowired service.
     *
     * @return \Ineersa\Tui\Application\TuiSessionSwitchService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Tui/Runtime/Contract/TuiSessionSwitchServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Tui/Application/TuiSessionSwitchService.php';
        include_once \dirname(__DIR__, 4).'/src/Tui/Question/QuestionCoordinator.php';

        return $container->privates['Ineersa\\Tui\\Application\\TuiSessionSwitchService'] = new \Ineersa\Tui\Application\TuiSessionSwitchService(($container->privates['Ineersa\\Tui\\Question\\QuestionCoordinator'] ??= new \Ineersa\Tui\Question\QuestionCoordinator()), ($container->privates['Ineersa\\Tui\\Question\\QuestionController'] ?? $container->load('getQuestionControllerService')), ($container->privates['Ineersa\\CodingAgent\\Runtime\\ProjectionPipeline\\TranscriptProjector'] ?? $container->load('getTranscriptProjectorService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
