<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToolCallExtractorService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\AgentCore\Application\Pipeline\ToolCallExtractor' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Pipeline\ToolCallExtractor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Pipeline/ToolCallExtractor.php';

        return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\ToolCallExtractor'] = new \Ineersa\AgentCore\Application\Pipeline\ToolCallExtractor();
    }
}
