<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Signing_Messenger_Transport_NativePhpSerializer_InnerService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private '.signing.messenger.transport.native_php_serializer.inner' shared service.
     *
     * @return \Symfony\Component\Messenger\Transport\Serialization\PhpSerializer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Serialization/SerializerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Serialization/MessageTypeAwareSerializerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Serialization/PhpSerializer.php';

        return $container->privates['.signing.messenger.transport.native_php_serializer.inner'] = new \Symfony\Component\Messenger\Transport\Serialization\PhpSerializer();
    }
}
