<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgentRunnerService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\AgentCore\Application\Pipeline\AgentRunner' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Pipeline\AgentRunner
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Contract/AgentRunnerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Pipeline/AgentRunner.php';

        $a = ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\AgentRunner'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\AgentRunner'];
        }
        $b = ($container->privates['serializer'] ?? self::getSerializerService($container));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\AgentRunner'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\AgentRunner'];
        }

        $instance = new \Ineersa\AgentCore\Application\Pipeline\AgentRunner($a, $b);

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\AgentRunner'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\AgentRunner'];
        }

        return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\AgentRunner'] = $instance;
    }
}
