<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCancelHandlerService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Runtime\Controller\CommandHandler\CancelHandler' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Runtime\Controller\CommandHandler\CancelHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Runtime/Controller/CommandHandler/CancelHandler.php';

        $a = ($container->privates['Ineersa\\CodingAgent\\Runtime\\InProcess\\InProcessAgentSessionClient'] ?? $container->load('getInProcessAgentSessionClientService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Runtime\\Controller\\CommandHandler\\CancelHandler'])) {
            return $container->privates['Ineersa\\CodingAgent\\Runtime\\Controller\\CommandHandler\\CancelHandler'];
        }

        $instance = new \Ineersa\CodingAgent\Runtime\Controller\CommandHandler\CancelHandler($a, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        if (isset($container->privates['Ineersa\\CodingAgent\\Runtime\\Controller\\CommandHandler\\CancelHandler'])) {
            return $container->privates['Ineersa\\CodingAgent\\Runtime\\Controller\\CommandHandler\\CancelHandler'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Runtime\\Controller\\CommandHandler\\CancelHandler'] = $instance;
    }
}
