<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompletionFileIndexRefreshCommand_LazyService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private '.Ineersa\CodingAgent\CLI\CompletionFileIndexRefreshCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Ineersa\\CodingAgent\\CLI\\CompletionFileIndexRefreshCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('completion:file-index:refresh', [], 'Rebuild the file mention completion index for the current project.', false, #[\Closure(name: 'Ineersa\\CodingAgent\\CLI\\CompletionFileIndexRefreshCommand')] fn (): \Ineersa\CodingAgent\CLI\CompletionFileIndexRefreshCommand => ($container->privates['Ineersa\\CodingAgent\\CLI\\CompletionFileIndexRefreshCommand'] ?? $container->load('getCompletionFileIndexRefreshCommandService')));
    }
}
