<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandParserService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\Tui\Command\CommandParser' shared autowired service.
     *
     * @return \Ineersa\Tui\Command\CommandParser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Tui/Command/CommandParser.php';

        return $container->privates['Ineersa\\Tui\\Command\\CommandParser'] = new \Ineersa\Tui\Command\CommandParser();
    }
}
