<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHitlProjectionSubscriberService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Runtime\ProjectionPipeline\HitlProjectionSubscriber' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Runtime\ProjectionPipeline\HitlProjectionSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Runtime/ProjectionPipeline/HitlProjectionSubscriber.php';

        return $container->privates['Ineersa\\CodingAgent\\Runtime\\ProjectionPipeline\\HitlProjectionSubscriber'] = new \Ineersa\CodingAgent\Runtime\ProjectionPipeline\HitlProjectionSubscriber();
    }
}
