<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromptEditorService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\Tui\Editor\PromptEditor' shared autowired service.
     *
     * @return \Ineersa\Tui\Editor\PromptEditor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Tui/Editor/PromptEditor.php';

        return $container->privates['Ineersa\\Tui\\Editor\\PromptEditor'] = new \Ineersa\Tui\Editor\PromptEditor();
    }
}
