<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRuntimeExceptionPolicySubscriberService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\EventListener\RuntimeExceptionPolicySubscriber' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\EventListener\RuntimeExceptionPolicySubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/EventListener/RuntimeExceptionPolicySubscriber.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Runtime/Contract/RuntimeErrorCaptureConfig.php';

        return $container->privates['Ineersa\\CodingAgent\\EventListener\\RuntimeExceptionPolicySubscriber'] = new \Ineersa\CodingAgent\EventListener\RuntimeExceptionPolicySubscriber(($container->privates['Ineersa\\CodingAgent\\Runtime\\Contract\\RuntimeErrorCaptureConfig'] ??= new \Ineersa\CodingAgent\Runtime\Contract\RuntimeErrorCaptureConfig($container->getEnv('bool:HATFIELD_CAPTURE_ERRORS'))), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
