<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSkillsContextBuilderService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Skills\SkillsContextBuilder' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Skills\SkillsContextBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Skills/SkillsContextBuilder.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Skills/SkillsConfig.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Skills/SkillContextRenderer.php';

        $a = ($container->privates['Ineersa\\CodingAgent\\Skills\\SkillDiscovery'] ?? $container->load('getSkillDiscoveryService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Skills\\SkillsContextBuilder'])) {
            return $container->privates['Ineersa\\CodingAgent\\Skills\\SkillsContextBuilder'];
        }

        $instance = new \Ineersa\CodingAgent\Skills\SkillsContextBuilder($a, ($container->privates['Ineersa\\CodingAgent\\Skills\\SkillsConfig'] ??= new \Ineersa\CodingAgent\Skills\SkillsConfig()), ($container->privates['Ineersa\\CodingAgent\\Skills\\SkillContextRenderer'] ??= new \Ineersa\CodingAgent\Skills\SkillContextRenderer()), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        if (isset($container->privates['Ineersa\\CodingAgent\\Skills\\SkillsContextBuilder'])) {
            return $container->privates['Ineersa\\CodingAgent\\Skills\\SkillsContextBuilder'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Skills\\SkillsContextBuilder'] = $instance;
    }
}
