<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getViewImageToolService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Tool\ViewImageTool' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Tool\ViewImageTool
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Tool/HatfieldToolProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Tool/ToolHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Tool/ViewImageTool.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Tool/StackToolExecutionContextAccessor.php';

        $a = ($container->privates['Ineersa\\CodingAgent\\Config\\ImageToolConfig'] ?? $container->load('getImageToolConfigService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\ViewImageTool'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\ViewImageTool'];
        }
        $b = ($container->privates['Ineersa\\CodingAgent\\Tool\\ImageProcessing\\RunVisionCheckService'] ?? $container->load('getRunVisionCheckServiceService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\ViewImageTool'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\ViewImageTool'];
        }

        $instance = new \Ineersa\CodingAgent\Tool\ViewImageTool(($container->privates['Ineersa\\CodingAgent\\Tool\\ToolRuntime'] ?? $container->load('getToolRuntimeService')), $a, ($container->privates['Ineersa\\AgentCore\\Application\\Tool\\StackToolExecutionContextAccessor'] ??= new \Ineersa\AgentCore\Application\Tool\StackToolExecutionContextAccessor()), $b, ($container->privates['Ineersa\\CodingAgent\\Tool\\ImageProcessing\\ImageAttachmentProcessor'] ?? $container->load('getImageAttachmentProcessorService')));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\ViewImageTool'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\ViewImageTool'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Tool\\ViewImageTool'] = $instance;
    }
}
