<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_HicAqfEService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.hicAqfE' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\ExecuteLlmStepWorker'] ?? $container->load('getExecuteLlmStepWorkerService'));

        if (isset($container->privates['.messenger.handler_descriptor.hicAqfE'])) {
            return $container->privates['.messenger.handler_descriptor.hicAqfE'];
        }

        $instance = new \Symfony\Component\Messenger\Handler\HandlerDescriptor($a, ['bus' => 'agent.execution.bus', 'method' => '__invoke']);

        if (isset($container->privates['.messenger.handler_descriptor.hicAqfE'])) {
            return $container->privates['.messenger.handler_descriptor.hicAqfE'];
        }

        return $container->privates['.messenger.handler_descriptor.hicAqfE'] = $instance;
    }
}
