<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgentMessageConverterService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\AgentCore\Infrastructure\SymfonyAi\AgentMessageConverter' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Infrastructure\SymfonyAi\AgentMessageConverter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\AgentMessageConverter'] = new \Ineersa\AgentCore\Infrastructure\SymfonyAi\AgentMessageConverter();
    }
}
