<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCopyCommandRegistrarService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\Tui\Listener\CopyCommandRegistrar' shared autowired service.
     *
     * @return \Ineersa\Tui\Listener\CopyCommandRegistrar
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\Tui\\Listener\\CopyCommandRegistrar'] = new \Ineersa\Tui\Listener\CopyCommandRegistrar(($container->privates['Ineersa\\Tui\\Command\\SlashCommandRegistry'] ??= new \Ineersa\Tui\Command\SlashCommandRegistry()));
    }
}
