<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsumerSupervisorService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Runtime\Controller\ConsumerSupervisor' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Runtime\Controller\ConsumerSupervisor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\CodingAgent\\Runtime\\Controller\\ConsumerSupervisor'] = new \Ineersa\CodingAgent\Runtime\Controller\ConsumerSupervisor(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->privates['Ineersa\\CodingAgent\\Runtime\\Process\\RuntimeProcessConfig'] ?? $container->load('getRuntimeProcessConfigService')));
    }
}
