<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_ArgumentResolver_MapInputService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'console.argument_resolver.map_input' shared service.
     *
     * @return \Symfony\Component\Console\ArgumentResolver\ValueResolver\MapInputValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['console.argument_resolver.map_input'] = new \Symfony\Component\Console\ArgumentResolver\ValueResolver\MapInputValueResolver(($container->privates['console.argument_resolver.builtin_type'] ??= new \Symfony\Component\Console\ArgumentResolver\ValueResolver\BuiltinTypeValueResolver()), ($container->privates['console.argument_resolver.backed_enum'] ??= new \Symfony\Component\Console\ArgumentResolver\ValueResolver\BackedEnumValueResolver()), ($container->privates['console.argument_resolver.datetime'] ?? $container->load('getConsole_ArgumentResolver_DatetimeService')), ($container->privates['validator'] ?? self::getValidatorService($container)));
    }
}
