<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHookSubscriberRegistryService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\AgentCore\Application\Handler\HookSubscriberRegistry' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Handler\HookSubscriberRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\HookSubscriberRegistry'] = new \Ineersa\AgentCore\Application\Handler\HookSubscriberRegistry(new RewindableGenerator(fn () => new \EmptyIterator(), 0));
    }
}
