<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModelSelectionServiceService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Config\ModelSelectionService' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Config\ModelSelectionService
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Config\\AppConfig'] ?? self::getAppConfigService($container));

        if (isset($container->privates['Ineersa\\CodingAgent\\Config\\ModelSelectionService'])) {
            return $container->privates['Ineersa\\CodingAgent\\Config\\ModelSelectionService'];
        }
        $b = ($container->privates['Ineersa\\CodingAgent\\Config\\ModelResolver'] ?? $container->load('getModelResolverService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Config\\ModelSelectionService'])) {
            return $container->privates['Ineersa\\CodingAgent\\Config\\ModelSelectionService'];
        }

        $instance = new \Ineersa\CodingAgent\Config\ModelSelectionService($a, $b, ($container->privates['Ineersa\\CodingAgent\\Config\\ModelSettingsPersister'] ?? $container->load('getModelSettingsPersisterService')));

        if (isset($container->privates['Ineersa\\CodingAgent\\Config\\ModelSelectionService'])) {
            return $container->privates['Ineersa\\CodingAgent\\Config\\ModelSelectionService'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Config\\ModelSelectionService'] = $instance;
    }
}
