<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRunMetricsService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\AgentCore\Application\Handler\RunMetrics' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Handler\RunMetrics
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunMetrics'] = new \Ineersa\AgentCore\Application\Handler\RunMetrics();
    }
}
