<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRuntimeEventMapperService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Runtime\Protocol\RuntimeEventMapper' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Runtime\Protocol\RuntimeEventMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Runtime\\Protocol\\RuntimeEventTranslator'] ?? $container->load('getRuntimeEventTranslatorService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Runtime\\Protocol\\RuntimeEventMapper'])) {
            return $container->privates['Ineersa\\CodingAgent\\Runtime\\Protocol\\RuntimeEventMapper'];
        }

        $instance = new \Ineersa\CodingAgent\Runtime\Protocol\RuntimeEventMapper($a);

        if (isset($container->privates['Ineersa\\CodingAgent\\Runtime\\Protocol\\RuntimeEventMapper'])) {
            return $container->privates['Ineersa\\CodingAgent\\Runtime\\Protocol\\RuntimeEventMapper'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Runtime\\Protocol\\RuntimeEventMapper'] = $instance;
    }
}
