<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRuntimeEventPollerService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\Tui\Runtime\RuntimeEventPoller' shared autowired service.
     *
     * @return \Ineersa\Tui\Runtime\RuntimeEventPoller
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\Tui\\Runtime\\RuntimeEventPoller'] = new \Ineersa\Tui\Runtime\RuntimeEventPoller(($container->privates['Ineersa\\CodingAgent\\Runtime\\ProjectionPipeline\\TranscriptProjector'] ?? $container->load('getTranscriptProjectorService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->privates['Ineersa\\CodingAgent\\Runtime\\Contract\\RuntimeExceptionBoundary'] ?? $container->load('getRuntimeExceptionBoundaryService')));
    }
}
