<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStartupDatabaseMigratorService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Migrations\StartupDatabaseMigrator' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Migrations\StartupDatabaseMigrator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\CodingAgent\\Migrations\\StartupDatabaseMigrator'] = new \Ineersa\CodingAgent\Migrations\StartupDatabaseMigrator(($container->privates['Ineersa\\CodingAgent\\Migrations\\ApplicationMigrationExecutor'] ?? $container->load('getApplicationMigrationExecutorService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
