<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigExecutableLocatorService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Runtime\Process\ConfigExecutableLocator' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Runtime\Process\ConfigExecutableLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Runtime/Process/AppExecutableLocator.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Runtime/Process/ConfigExecutableLocator.php';

        return $container->privates['Ineersa\\CodingAgent\\Runtime\\Process\\ConfigExecutableLocator'] = new \Ineersa\CodingAgent\Runtime\Process\ConfigExecutableLocator($container->getEnv('default:kernel.project_dir:string:HATFIELD_CWD'));
    }
}
