<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExecuteToolCallWorkerService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\AgentCore\Application\Handler\ExecuteToolCallWorker' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Handler\ExecuteToolCallWorker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Handler/ExecuteToolCallWorker.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Handler/RunMetrics.php';

        $a = ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\ToolExecutor'] ?? $container->load('getToolExecutorService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Handler\\ExecuteToolCallWorker'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\ExecuteToolCallWorker'];
        }
        $b = ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Handler\\ExecuteToolCallWorker'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\ExecuteToolCallWorker'];
        }

        $instance = new \Ineersa\AgentCore\Application\Handler\ExecuteToolCallWorker($a, $b, ($container->privates['Ineersa\\CodingAgent\\Session\\SessionRunStore'] ?? $container->load('getSessionRunStoreService')), ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunMetrics'] ??= new \Ineersa\AgentCore\Application\Handler\RunMetrics()), ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunTracer'] ?? $container->load('getRunTracerService')));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Handler\\ExecuteToolCallWorker'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\ExecuteToolCallWorker'];
        }

        return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\ExecuteToolCallWorker'] = $instance;
    }
}
