<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_ReceiverLocatorService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'messenger.receiver_locator' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['messenger.receiver_locator'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'messenger.transport.run_control' => ['privates', 'messenger.transport.run_control', 'getMessenger_Transport_RunControlService', true],
            'run_control' => ['privates', 'messenger.transport.run_control', 'getMessenger_Transport_RunControlService', true],
            'messenger.transport.llm' => ['privates', 'messenger.transport.llm', 'getMessenger_Transport_LlmService', true],
            'llm' => ['privates', 'messenger.transport.llm', 'getMessenger_Transport_LlmService', true],
            'messenger.transport.tool' => ['privates', 'messenger.transport.tool', 'getMessenger_Transport_ToolService', true],
            'tool' => ['privates', 'messenger.transport.tool', 'getMessenger_Transport_ToolService', true],
            'messenger.transport.scheduler_default' => ['privates', 'messenger.transport.scheduler_default', 'getMessenger_Transport_SchedulerDefaultService', true],
            'scheduler_default' => ['privates', 'messenger.transport.scheduler_default', 'getMessenger_Transport_SchedulerDefaultService', true],
        ], [
            'messenger.transport.run_control' => '?',
            'run_control' => '?',
            'messenger.transport.llm' => '?',
            'llm' => '?',
            'messenger.transport.tool' => '?',
            'tool' => '?',
            'messenger.transport.scheduler_default' => '?',
            'scheduler_default' => '?',
        ]);
    }
}
