<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistryBackedToolboxService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Tool\RegistryBackedToolbox' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Tool\RegistryBackedToolbox
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ai-agent/src/Toolbox/ToolboxInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Tool/RegistryBackedToolbox.php';

        $a = ($container->privates['Ineersa\\CodingAgent\\Tool\\ToolRegistry'] ?? $container->load('getToolRegistryService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\RegistryBackedToolbox'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\RegistryBackedToolbox'];
        }
        $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\RegistryBackedToolbox'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\RegistryBackedToolbox'];
        }

        $instance = new \Ineersa\CodingAgent\Tool\RegistryBackedToolbox($a, $b);

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\RegistryBackedToolbox'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\RegistryBackedToolbox'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Tool\\RegistryBackedToolbox'] = $instance;
    }
}
