<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Lock_Flock_StoreService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private '.lock.flock.store' shared service.
     *
     * @return \Symfony\Component\Lock\Store\FlockStore
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.lock.flock.store'] = new \Symfony\Component\Lock\Store\FlockStore(\implode('/', [\sys_get_temp_dir(), 'symfony-lock', \hash('xxh64', 'phar:///home/ineersa/projects/agent-core-worktrees/maint-01-test-suite-maintenance-isolation-cleanup-flaky-gates/var/tmp/phar/hatfield.phar')]));
    }
}
