<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgent_Execution_Bus_Middleware_HandleMessageService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'agent.execution.bus.middleware.handle_message' shared service.
     *
     * @return \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator(['Ineersa\\AgentCore\\Domain\\Message\\ExecuteLlmStep' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.hicAqfE'] ?? $container->load('get_Messenger_HandlerDescriptor_HicAqfEService'));
        }, 1), 'Ineersa\\AgentCore\\Domain\\Message\\ExecuteToolCall' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.9JusjcH'] ?? $container->load('get_Messenger_HandlerDescriptor_9JusjcHService'));
        }, 1), 'Symfony\\Component\\Process\\Messenger\\RunProcessMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.2IYpJH8'] ?? $container->load('get_Messenger_HandlerDescriptor_2IYpJH8Service'));
        }, 1), 'Symfony\\Component\\Console\\Messenger\\RunCommandMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.Jfy4_s8'] ?? $container->load('get_Messenger_HandlerDescriptor_Jfy4S8Service'));
        }, 1), 'Symfony\\Component\\HttpClient\\Messenger\\PingWebhookMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.mD3SEQf'] ?? $container->load('get_Messenger_HandlerDescriptor_MD3SEQfService'));
        }, 1), 'Symfony\\Component\\Scheduler\\Messenger\\ServiceCallMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.mdnjiVd'] ?? $container->load('get_Messenger_HandlerDescriptor_MdnjiVdService'));
        }, 1), 'Symfony\\Component\\Messenger\\Message\\RedispatchMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.ARP4Civ'] ?? $container->load('get_Messenger_HandlerDescriptor_ARP4CivService'));
        }, 1)]), false, ($container->privates['clock'] ??= new \Symfony\Component\Clock\Clock()), false);

        if (isset($container->privates['agent.execution.bus.middleware.handle_message'])) {
            return $container->privates['agent.execution.bus.middleware.handle_message'];
        }

        $container->privates['agent.execution.bus.middleware.handle_message'] = $instance;

        $instance->setLogger(($container->privates['monolog.logger.messenger'] ?? $container->load('getMonolog_Logger_MessengerService')));

        return $instance;
    }
}
