<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgent_Execution_BusService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'agent.execution.bus' shared service.
     *
     * @return \Symfony\Component\Messenger\MessageBus
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\Messenger\MessageBus(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['messenger.middleware.add_default_stamps_middleware'] ??= new \Symfony\Component\Messenger\Middleware\AddDefaultStampsMiddleware());
            yield 1 => ($container->privates['agent.execution.bus.middleware.add_bus_name_stamp_middleware'] ??= new \Symfony\Component\Messenger\Middleware\AddBusNameStampMiddleware('agent.execution.bus'));
            yield 2 => ($container->privates['messenger.middleware.reject_redelivered_message_middleware'] ??= new \Symfony\Component\Messenger\Middleware\RejectRedeliveredMessageMiddleware());
            yield 3 => ($container->privates['messenger.middleware.dispatch_after_current_bus'] ??= new \Symfony\Component\Messenger\Middleware\DispatchAfterCurrentBusMiddleware());
            yield 4 => ($container->privates['messenger.middleware.decode_failed_message_middleware'] ?? $container->load('getMessenger_Middleware_DecodeFailedMessageMiddlewareService'));
            yield 5 => ($container->privates['messenger.middleware.failed_message_processing_middleware'] ??= new \Symfony\Component\Messenger\Middleware\FailedMessageProcessingMiddleware());
            yield 6 => ($container->privates['messenger.middleware.deduplicate_middleware'] ?? $container->load('getMessenger_Middleware_DeduplicateMiddlewareService'));
            yield 7 => ($container->privates['agent.execution.bus.middleware.send_message'] ?? $container->load('getAgent_Execution_Bus_Middleware_SendMessageService'));
            yield 8 => ($container->privates['agent.execution.bus.middleware.handle_message'] ?? $container->load('getAgent_Execution_Bus_Middleware_HandleMessageService'));
        }, 9));

        if (isset($container->privates['agent.execution.bus'])) {
            return $container->privates['agent.execution.bus'];
        }

        return $container->privates['agent.execution.bus'] = $instance;
    }
}
