<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnswerToolQuestionHandlerService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Runtime\Controller\CommandHandler\AnswerToolQuestionHandler' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Runtime\Controller\CommandHandler\AnswerToolQuestionHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\ToolQuestionStore'] ?? $container->load('getToolQuestionStoreService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Runtime\\Controller\\CommandHandler\\AnswerToolQuestionHandler'])) {
            return $container->privates['Ineersa\\CodingAgent\\Runtime\\Controller\\CommandHandler\\AnswerToolQuestionHandler'];
        }

        $instance = new \Ineersa\CodingAgent\Runtime\Controller\CommandHandler\AnswerToolQuestionHandler($a, ($container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\ToolQuestionAnswerResolver'] ??= new \Ineersa\CodingAgent\Tool\ToolQuestion\ToolQuestionAnswerResolver()));

        if (isset($container->privates['Ineersa\\CodingAgent\\Runtime\\Controller\\CommandHandler\\AnswerToolQuestionHandler'])) {
            return $container->privates['Ineersa\\CodingAgent\\Runtime\\Controller\\CommandHandler\\AnswerToolQuestionHandler'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Runtime\\Controller\\CommandHandler\\AnswerToolQuestionHandler'] = $instance;
    }
}
