<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackgroundProcessRepositoryService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Entity\BackgroundProcessRepository' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Entity\BackgroundProcessRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\CodingAgent\\Entity\\BackgroundProcessRepository'] = new \Ineersa\CodingAgent\Entity\BackgroundProcessRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
