<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackgroundProcessManagerService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Tool\BackgroundProcessManager' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Tool\BackgroundProcessManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcess\\ProcessStore'] ?? $container->load('getProcessStoreService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcessManager'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcessManager'];
        }
        $b = ($container->privates['Ineersa\\CodingAgent\\Config\\BackgroundProcessConfig'] ?? $container->load('getBackgroundProcessConfigService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcessManager'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcessManager'];
        }
        $c = ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'));

        $instance = new \Ineersa\CodingAgent\Tool\BackgroundProcessManager($a, new \Ineersa\CodingAgent\Tool\BackgroundProcess\ProcessLifecycle($b, $c), $b, $c);

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcessManager'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcessManager'];
        }

        $container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcessManager'] = $instance;

        $instance->registerShutdownHandler();

        return $instance;
    }
}
