<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_ArgumentResolver_BackedEnumService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'console.argument_resolver.backed_enum' shared service.
     *
     * @return \Symfony\Component\Console\ArgumentResolver\ValueResolver\BackedEnumValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['console.argument_resolver.backed_enum'] = new \Symfony\Component\Console\ArgumentResolver\ValueResolver\BackedEnumValueResolver();
    }
}
