<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebug_ErrorHandlerConfiguratorService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the public 'debug.error_handler_configurator' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Debug\ErrorHandlerConfigurator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = new \Monolog\Logger('php');
        $a->pushHandler(($container->privates['Ineersa\\CodingAgent\\Logging\\HatfieldRotatingLogHandler'] ?? self::getHatfieldRotatingLogHandlerService($container)));
        $a->pushProcessor(($container->privates['Ineersa\\CodingAgent\\Logging\\LogContextProcessor'] ??= new \Ineersa\CodingAgent\Logging\LogContextProcessor()));

        return $container->services['debug.error_handler_configurator'] = new \Symfony\Component\HttpKernel\Debug\ErrorHandlerConfigurator($a, [16384 => 'debug'], 0, false, false, NULL);
    }
}
