<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHatfieldSessionStoreService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Session\HatfieldSessionStore' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Session\HatfieldSessionStore
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Config\\AppConfig'] ?? self::getAppConfigService($container));

        if (isset($container->privates['Ineersa\\CodingAgent\\Session\\HatfieldSessionStore'])) {
            return $container->privates['Ineersa\\CodingAgent\\Session\\HatfieldSessionStore'];
        }
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['Ineersa\\CodingAgent\\Session\\HatfieldSessionStore'])) {
            return $container->privates['Ineersa\\CodingAgent\\Session\\HatfieldSessionStore'];
        }

        $instance = new \Ineersa\CodingAgent\Session\HatfieldSessionStore($a, $b);

        if (isset($container->privates['Ineersa\\CodingAgent\\Session\\HatfieldSessionStore'])) {
            return $container->privates['Ineersa\\CodingAgent\\Session\\HatfieldSessionStore'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Session\\HatfieldSessionStore'] = $instance;
    }
}
