<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Failure_ReleaseDeduplicationLockOnFailureListenerService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'messenger.failure.release_deduplication_lock_on_failure_listener' shared service.
     *
     * @return \Symfony\Component\Messenger\EventListener\ReleaseDeduplicationLockOnFailureListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['lock.default.factory'] ?? $container->load('getLock_Default_FactoryService'));

        if (isset($container->privates['messenger.failure.release_deduplication_lock_on_failure_listener'])) {
            return $container->privates['messenger.failure.release_deduplication_lock_on_failure_listener'];
        }

        $instance = new \Symfony\Component\Messenger\EventListener\ReleaseDeduplicationLockOnFailureListener($a);

        if (isset($container->privates['messenger.failure.release_deduplication_lock_on_failure_listener'])) {
            return $container->privates['messenger.failure.release_deduplication_lock_on_failure_listener'];
        }

        return $container->privates['messenger.failure.release_deduplication_lock_on_failure_listener'] = $instance;
    }
}
