<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModelResolverRoutingSubscriberService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\AgentCore\Infrastructure\SymfonyAi\ModelResolverRoutingSubscriber' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Infrastructure\SymfonyAi\ModelResolverRoutingSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Infrastructure\\SymfonyAi\\SymfonyAiProviderFactory'] ?? $container->load('getSymfonyAiProviderFactoryService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\ModelResolverRoutingSubscriber'])) {
            return $container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\ModelResolverRoutingSubscriber'];
        }

        $instance = new \Ineersa\AgentCore\Infrastructure\SymfonyAi\ModelResolverRoutingSubscriber(new \Ineersa\CodingAgent\Config\SessionAwareModelResolver(($container->privates['Ineersa\\CodingAgent\\Config\\ModelSelectionService'] ?? $container->load('getModelSelectionServiceService'))), new \Ineersa\CodingAgent\Infrastructure\SymfonyAi\SymfonyAiProviderRegistry($a));

        if (isset($container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\ModelResolverRoutingSubscriber'])) {
            return $container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\ModelResolverRoutingSubscriber'];
        }

        return $container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\ModelResolverRoutingSubscriber'] = $instance;
    }
}
