<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Transport_RunControlService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'messenger.transport.run_control' shared service.
     *
     * @return \Symfony\Component\Messenger\Transport\TransportInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['messenger.transport_factory'] ?? $container->load('getMessenger_TransportFactoryService'));

        if (isset($container->privates['messenger.transport.run_control'])) {
            return $container->privates['messenger.transport.run_control'];
        }

        $instance = $a->createTransport($container->getEnv('HATFIELD_RUN_CONTROL_TRANSPORT_DSN'), ['transport_name' => 'run_control'], ($container->privates['.signing.messenger.transport.native_php_serializer'] ?? $container->load('get_Signing_Messenger_Transport_NativePhpSerializerService')));

        if (isset($container->privates['messenger.transport.run_control'])) {
            return $container->privates['messenger.transport.run_control'];
        }

        return $container->privates['messenger.transport.run_control'] = $instance;
    }
}
