<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOutputCapService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Tool\OutputCap' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Tool\OutputCap
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Config\\AppConfig'] ?? self::getAppConfigService($container));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\OutputCap'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\OutputCap'];
        }

        $instance = new \Ineersa\CodingAgent\Tool\OutputCap(\Ineersa\CodingAgent\Config\OutputCapConfig::fromAppConfig($a));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\OutputCap'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\OutputCap'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Tool\\OutputCap'] = $instance;
    }
}
