<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessStoreService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Tool\BackgroundProcess\ProcessStore' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Tool\BackgroundProcess\ProcessStore
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcess\\ProcessStore'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcess\\ProcessStore'];
        }

        $instance = new \Ineersa\CodingAgent\Tool\BackgroundProcess\ProcessStore($a, ($container->privates['Ineersa\\CodingAgent\\Entity\\BackgroundProcessRepository'] ?? $container->load('getBackgroundProcessRepositoryService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcess\\ProcessStore'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcess\\ProcessStore'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcess\\ProcessStore'] = $instance;
    }
}
