<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScheduler_Provider_DefaultService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'scheduler.provider.default' shared service.
     *
     * @return \Symfony\Component\Scheduler\Schedule
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['scheduler.provider.default'] = $instance = new \Symfony\Component\Scheduler\Schedule();

        $instance->add(\Symfony\Component\Scheduler\RecurringMessage::every(30, new \Symfony\Component\Console\Messenger\RunCommandMessage('completion:file-index:refresh')));

        return $instance;
    }
}
