<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionRunEventStoreService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Session\SessionRunEventStore' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Session\SessionRunEventStore
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Session\\HatfieldSessionStore'] ?? $container->load('getHatfieldSessionStoreService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Session\\SessionRunEventStore'])) {
            return $container->privates['Ineersa\\CodingAgent\\Session\\SessionRunEventStore'];
        }
        $b = ($container->privates['lock.default.factory'] ?? $container->load('getLock_Default_FactoryService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Session\\SessionRunEventStore'])) {
            return $container->privates['Ineersa\\CodingAgent\\Session\\SessionRunEventStore'];
        }
        $c = ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Session\\SessionRunEventStore'])) {
            return $container->privates['Ineersa\\CodingAgent\\Session\\SessionRunEventStore'];
        }

        $instance = new \Ineersa\CodingAgent\Session\SessionRunEventStore($a, new \Ineersa\AgentCore\Schema\EventPayloadNormalizer(), $b, $c);

        if (isset($container->privates['Ineersa\\CodingAgent\\Session\\SessionRunEventStore'])) {
            return $container->privates['Ineersa\\CodingAgent\\Session\\SessionRunEventStore'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Session\\SessionRunEventStore'] = $instance;
    }
}
