<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionRunStoreService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Session\SessionRunStore' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Session\SessionRunStore
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Session\\HatfieldSessionStore'] ?? $container->load('getHatfieldSessionStoreService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Session\\SessionRunStore'])) {
            return $container->privates['Ineersa\\CodingAgent\\Session\\SessionRunStore'];
        }
        $b = ($container->privates['serializer'] ?? self::getSerializerService($container));

        if (isset($container->privates['Ineersa\\CodingAgent\\Session\\SessionRunStore'])) {
            return $container->privates['Ineersa\\CodingAgent\\Session\\SessionRunStore'];
        }
        $c = ($container->privates['lock.default.factory'] ?? $container->load('getLock_Default_FactoryService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Session\\SessionRunStore'])) {
            return $container->privates['Ineersa\\CodingAgent\\Session\\SessionRunStore'];
        }

        $instance = new \Ineersa\CodingAgent\Session\SessionRunStore($a, $b, $c);

        if (isset($container->privates['Ineersa\\CodingAgent\\Session\\SessionRunStore'])) {
            return $container->privates['Ineersa\\CodingAgent\\Session\\SessionRunStore'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Session\\SessionRunStore'] = $instance;
    }
}
