<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStartRunHandlerService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\AgentCore\Application\Pipeline\StartRunHandler' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Pipeline\StartRunHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['serializer'] ?? self::getSerializerService($container));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\StartRunHandler'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\StartRunHandler'];
        }
        $b = ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\StartRunHandler'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\StartRunHandler'];
        }

        $instance = new \Ineersa\AgentCore\Application\Pipeline\StartRunHandler(($container->privates['Ineersa\\AgentCore\\Domain\\Event\\EventFactory'] ??= new \Ineersa\AgentCore\Domain\Event\EventFactory()), $a, $b);

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\StartRunHandler'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\StartRunHandler'];
        }

        return $container->privates['Ineersa\\AgentCore\\Application\\Pipeline\\StartRunHandler'] = $instance;
    }
}
