<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTickPollListenerService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\Tui\Listener\TickPollListener' shared autowired service.
     *
     * @return \Ineersa\Tui\Listener\TickPollListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\Tui\\Listener\\TickPollListener'] = new \Ineersa\Tui\Listener\TickPollListener(new \Ineersa\Tui\Runtime\RuntimeEventPoller(($container->privates['Ineersa\\CodingAgent\\Runtime\\ProjectionPipeline\\TranscriptProjector'] ?? $container->load('getTranscriptProjectorService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->privates['Ineersa\\CodingAgent\\Runtime\\Contract\\RuntimeExceptionBoundary'] ?? $container->load('getRuntimeExceptionBoundaryService'))), ($container->privates['Ineersa\\Tui\\Question\\QuestionCoordinator'] ??= new \Ineersa\Tui\Question\QuestionCoordinator()), ($container->privates['Ineersa\\Tui\\Question\\QuestionController'] ?? $container->load('getQuestionControllerService')));
    }
}
