<?php

namespace ContainerLwFcCHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToolBatchCollectorService extends Ineersa_CodingAgent_KernelProdContainer
{
    /*
     * Gets the private 'Ineersa\AgentCore\Application\Handler\ToolBatchCollector' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Handler\ToolBatchCollector
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Handler\\ToolBatchCollector'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\ToolBatchCollector'];
        }

        $instance = new \Ineersa\AgentCore\Application\Handler\ToolBatchCollector(4, new \Ineersa\CodingAgent\Tool\Store\DbalToolBatchStore($a, ($container->privates['Ineersa\\CodingAgent\\Entity\\ToolBatchStateRepository'] ?? $container->load('getToolBatchStateRepositoryService'))));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Handler\\ToolBatchCollector'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\ToolBatchCollector'];
        }

        return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\ToolBatchCollector'] = $instance;
    }
}
