<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackgroundProcessCompletionPollerService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Runtime\Controller\BackgroundProcessCompletionPoller' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Runtime\Controller\BackgroundProcessCompletionPoller
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\CodingAgent\\Runtime\\Controller\\BackgroundProcessCompletionPoller'] = new \Ineersa\CodingAgent\Runtime\Controller\BackgroundProcessCompletionPoller(($container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcess\\ProcessStore'] ?? $container->load('getProcessStoreService')), ($container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcessManager'] ?? $container->load('getBackgroundProcessManagerService')), ($container->privates['Ineersa\\CodingAgent\\Runtime\\InProcess\\InProcessAgentSessionClient'] ?? $container->load('getInProcessAgentSessionClientService')), ($container->privates['Ineersa\\CodingAgent\\Runtime\\Controller\\RuntimeEventEmitter'] ?? $container->load('getRuntimeEventEmitterService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), $container->getEnv('HATFIELD_SESSION_ID'));
    }
}
