<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCodexAuthCommand_CommandService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\CLI\Auth\CodexAuthCommand.command' shared service.
     *
     * @return \Symfony\Component\Console\Command\Command
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Ineersa\\CodingAgent\\CLI\\Auth\\CodexAuthCommand.command'] = $instance = new \Symfony\Component\Console\Command\Command();

        $instance->setCode(($container->privates['Ineersa\\CodingAgent\\CLI\\Auth\\CodexAuthCommand'] ?? $container->load('getCodexAuthCommandService'))->__invoke(...));
        $instance->setName('auth:codex');
        $instance->setDescription('Authenticate with OpenAI Codex subscription (OAuth PKCE)');

        return $instance;
    }
}
