<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChainExecutableLocatorService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Runtime\Process\ChainExecutableLocator' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Runtime\Process\ChainExecutableLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\CodingAgent\\Runtime\\Process\\ChainExecutableLocator'] = new \Ineersa\CodingAgent\Runtime\Process\ChainExecutableLocator(($container->privates['Ineersa\\CodingAgent\\Runtime\\Process\\ConfigExecutableLocator'] ??= new \Ineersa\CodingAgent\Runtime\Process\ConfigExecutableLocator($container->getEnv('default:kernel.project_dir:string:HATFIELD_CWD'))), ($container->privates['Ineersa\\CodingAgent\\Runtime\\Process\\PharExecutableLocator'] ??= new \Ineersa\CodingAgent\Runtime\Process\PharExecutableLocator()), ($container->privates['Ineersa\\CodingAgent\\Runtime\\Process\\SourceTreeExecutableLocator'] ??= new \Ineersa\CodingAgent\Runtime\Process\SourceTreeExecutableLocator(\dirname(__DIR__, 4))));
    }
}
