<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCancelListenerService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\Tui\Listener\CancelListener' shared autowired service.
     *
     * @return \Ineersa\Tui\Listener\CancelListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\Tui\\Listener\\CancelListener'] = new \Ineersa\Tui\Listener\CancelListener(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->privates['Ineersa\\CodingAgent\\Runtime\\Contract\\RuntimeExceptionBoundary'] ?? $container->load('getRuntimeExceptionBoundaryService')));
    }
}
