<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExtensionHookRegistryService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Extension\ExtensionHookRegistry' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Extension\ExtensionHookRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\CodingAgent\\Extension\\ExtensionHookRegistry'] = new \Ineersa\CodingAgent\Extension\ExtensionHookRegistry();
    }
}
