<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExecuteLlmStepWorkerService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\AgentCore\Application\Handler\ExecuteLlmStepWorker' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Handler\ExecuteLlmStepWorker
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\LlmPlatformAdapter'] ?? $container->load('getLlmPlatformAdapterService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Handler\\ExecuteLlmStepWorker'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\ExecuteLlmStepWorker'];
        }
        $b = ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Handler\\ExecuteLlmStepWorker'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\ExecuteLlmStepWorker'];
        }

        $instance = new \Ineersa\AgentCore\Application\Handler\ExecuteLlmStepWorker($a, $b, '', ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunMetrics'] ??= new \Ineersa\AgentCore\Application\Handler\RunMetrics()), ($container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunTracer'] ?? $container->load('getRunTracerService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Handler\\ExecuteLlmStepWorker'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\ExecuteLlmStepWorker'];
        }

        return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\ExecuteLlmStepWorker'] = $instance;
    }
}
