<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFooterStateInitializerService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\Tui\Listener\FooterStateInitializer' shared autowired service.
     *
     * @return \Ineersa\Tui\Listener\FooterStateInitializer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\Tui\\Listener\\FooterStateInitializer'] = new \Ineersa\Tui\Listener\FooterStateInitializer(($container->privates['Ineersa\\CodingAgent\\Session\\HatfieldSessionStore'] ?? $container->load('getHatfieldSessionStoreService')), ($container->privates['Ineersa\\CodingAgent\\Config\\AppConfig'] ?? self::getAppConfigService($container)));
    }
}
