<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFavoritePickerControllerService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\Tui\Picker\FavoritePickerController' shared autowired service.
     *
     * @return \Ineersa\Tui\Picker\FavoritePickerController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\Tui\\Picker\\FavoritePickerController'] = new \Ineersa\Tui\Picker\FavoritePickerController(($container->privates['Ineersa\\CodingAgent\\Config\\ModelSelectionService'] ?? $container->load('getModelSelectionServiceService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
