<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInMemoryCommandStoreService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\AgentCore\Infrastructure\Storage\InMemoryCommandStore' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Infrastructure\Storage\InMemoryCommandStore
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\AgentCore\\Infrastructure\\Storage\\InMemoryCommandStore'] = new \Ineersa\AgentCore\Infrastructure\Storage\InMemoryCommandStore();
    }
}
