<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInteractiveModeService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\Tui\Application\InteractiveMode' shared autowired service.
     *
     * @return \Ineersa\Tui\Application\InteractiveMode
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\Tui\\Application\\InteractiveMode'] = new \Ineersa\Tui\Application\InteractiveMode(($container->privates['Ineersa\\CodingAgent\\Session\\HatfieldSessionStore'] ?? $container->load('getHatfieldSessionStoreService')), ($container->privates['Ineersa\\Tui\\Application\\ThemeFactory'] ?? $container->load('getThemeFactoryService')), ($container->privates['Ineersa\\Tui\\Application\\SessionInitializer'] ?? $container->load('getSessionInitializerService')), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Ineersa\\CodingAgent\\CLI\\FileMentionIndexStartupListener'] ?? $container->load('getFileMentionIndexStartupListenerService'));
            yield 1 => ($container->privates['Ineersa\\Tui\\Listener\\CancelListener'] ?? $container->load('getCancelListenerService'));
            yield 2 => ($container->privates['Ineersa\\Tui\\Listener\\CompletionListener'] ?? $container->load('getCompletionListenerService'));
            yield 3 => ($container->privates['Ineersa\\Tui\\Listener\\CopyCommandRegistrar'] ?? $container->load('getCopyCommandRegistrarService'));
            yield 4 => ($container->privates['Ineersa\\Tui\\Listener\\CtrlCInputInterceptor'] ??= new \Ineersa\Tui\Listener\CtrlCInputInterceptor());
            yield 5 => ($container->privates['Ineersa\\Tui\\Listener\\FooterStateListener'] ?? $container->load('getFooterStateListenerService'));
            yield 6 => ($container->privates['Ineersa\\Tui\\Listener\\ModelControlListener'] ?? $container->load('getModelControlListenerService'));
            yield 7 => ($container->privates['Ineersa\\Tui\\Listener\\PromptHistoryListener'] ??= new \Ineersa\Tui\Listener\PromptHistoryListener());
            yield 8 => ($container->privates['Ineersa\\Tui\\Listener\\QuitListener'] ??= new \Ineersa\Tui\Listener\QuitListener());
            yield 9 => ($container->privates['Ineersa\\Tui\\Listener\\SessionCommandRegistrar'] ?? $container->load('getSessionCommandRegistrarService'));
            yield 10 => ($container->privates['Ineersa\\Tui\\Listener\\SubmitListener'] ?? $container->load('getSubmitListenerService'));
            yield 11 => ($container->privates['Ineersa\\Tui\\Listener\\TickPollListener'] ?? $container->load('getTickPollListenerService'));
        }, 12), ($container->privates['Ineersa\\Tui\\Editor\\PromptEditor'] ??= new \Ineersa\Tui\Editor\PromptEditor()), ($container->privates['Ineersa\\Tui\\Transcript\\TranscriptBlockFactory'] ??= new \Ineersa\Tui\Transcript\TranscriptBlockFactory()), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->privates['Ineersa\\Tui\\Application\\TuiSessionSwitchService'] ?? $container->load('getTuiSessionSwitchServiceService')));
    }
}
