<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageIdempotencyServiceService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\AgentCore\Application\Handler\MessageIdempotencyService' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Handler\MessageIdempotencyService
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Session\\JsonlIdempotencyStore'] ?? $container->load('getJsonlIdempotencyStoreService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Handler\\MessageIdempotencyService'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\MessageIdempotencyService'];
        }

        $instance = new \Ineersa\AgentCore\Application\Handler\MessageIdempotencyService($a);

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Handler\\MessageIdempotencyService'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\MessageIdempotencyService'];
        }

        return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\MessageIdempotencyService'] = $instance;
    }
}
