<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOutputCapLlmTransformHookService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Tool\OutputCapLlmTransformHook' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Tool\OutputCapLlmTransformHook
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\CodingAgent\\Tool\\OutputCapLlmTransformHook'] = new \Ineersa\CodingAgent\Tool\OutputCapLlmTransformHook(($container->privates['Ineersa\\CodingAgent\\Tool\\OutputCap'] ?? $container->load('getOutputCapService')));
    }
}
