<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessLifecycleService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Tool\BackgroundProcess\ProcessLifecycle' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Tool\BackgroundProcess\ProcessLifecycle
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Config\\BackgroundProcessConfig'] ?? $container->load('getBackgroundProcessConfigService'));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcess\\ProcessLifecycle'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcess\\ProcessLifecycle'];
        }

        $instance = new \Ineersa\CodingAgent\Tool\BackgroundProcess\ProcessLifecycle($a, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        if (isset($container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcess\\ProcessLifecycle'])) {
            return $container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcess\\ProcessLifecycle'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Tool\\BackgroundProcess\\ProcessLifecycle'] = $instance;
    }
}
