<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuestionControllerService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\Tui\Question\QuestionController' shared autowired service.
     *
     * @return \Ineersa\Tui\Question\QuestionController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\Tui\\Question\\QuestionController'] = new \Ineersa\Tui\Question\QuestionController(($container->privates['Ineersa\\Tui\\Question\\QuestionCoordinator'] ??= new \Ineersa\Tui\Question\QuestionCoordinator()));
    }
}
