<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRunLockManagerService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\AgentCore\Application\Handler\RunLockManager' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Handler\RunLockManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['lock.default.factory'] ?? $container->load('getLock_Default_FactoryService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunLockManager'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunLockManager'];
        }

        $instance = new \Ineersa\AgentCore\Application\Handler\RunLockManager($a);

        if (isset($container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunLockManager'])) {
            return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunLockManager'];
        }

        return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunLockManager'] = $instance;
    }
}
