<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToolQuestionAnswerResolverService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Tool\ToolQuestion\ToolQuestionAnswerResolver' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Tool\ToolQuestion\ToolQuestionAnswerResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\CodingAgent\\Tool\\ToolQuestion\\ToolQuestionAnswerResolver'] = new \Ineersa\CodingAgent\Tool\ToolQuestion\ToolQuestionAnswerResolver();
    }
}
