<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemeFactoryService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\Tui\Application\ThemeFactory' shared autowired service.
     *
     * @return \Ineersa\Tui\Application\ThemeFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\Tui\\Application\\ThemeFactory'] = new \Ineersa\Tui\Application\ThemeFactory(($container->privates['Ineersa\\CodingAgent\\Config\\AppConfig'] ?? self::getAppConfigService($container)), ($container->privates['Ineersa\\Tui\\Theme\\ThemeRegistry'] ?? $container->load('getThemeRegistryService')));
    }
}
