<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTranscriptProjectionStateService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\CodingAgent\Runtime\Projection\TranscriptProjectionState' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Runtime\Projection\TranscriptProjectionState
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Ineersa\\CodingAgent\\Runtime\\Projection\\TranscriptProjectionState'] = new \Ineersa\CodingAgent\Runtime\Projection\TranscriptProjectionState();
    }
}
