<?php

namespace ContainerCKKBfsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkerFailedEventSubscriberService extends Ineersa_CodingAgent_KernelTestContainer
{
    /*
     * Gets the private 'Ineersa\AgentCore\Infrastructure\Messenger\WorkerFailedEventSubscriber' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Infrastructure\Messenger\WorkerFailedEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Ineersa\\CodingAgent\\Session\\SessionRunStore'] ?? $container->load('getSessionRunStoreService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Infrastructure\\Messenger\\WorkerFailedEventSubscriber'])) {
            return $container->privates['Ineersa\\AgentCore\\Infrastructure\\Messenger\\WorkerFailedEventSubscriber'];
        }
        $b = ($container->privates['Ineersa\\CodingAgent\\Session\\SessionRunEventStore'] ?? $container->load('getSessionRunEventStoreService'));

        if (isset($container->privates['Ineersa\\AgentCore\\Infrastructure\\Messenger\\WorkerFailedEventSubscriber'])) {
            return $container->privates['Ineersa\\AgentCore\\Infrastructure\\Messenger\\WorkerFailedEventSubscriber'];
        }

        $instance = new \Ineersa\AgentCore\Infrastructure\Messenger\WorkerFailedEventSubscriber($a, $b, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        if (isset($container->privates['Ineersa\\AgentCore\\Infrastructure\\Messenger\\WorkerFailedEventSubscriber'])) {
            return $container->privates['Ineersa\\AgentCore\\Infrastructure\\Messenger\\WorkerFailedEventSubscriber'];
        }

        return $container->privates['Ineersa\\AgentCore\\Infrastructure\\Messenger\\WorkerFailedEventSubscriber'] = $instance;
    }
}
