<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_W0pGDBTService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.W0pGDBT' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';

        return $container->privates['.messenger.handler_descriptor.W0pGDBT'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->privates['console.messenger.execute_command_handler'] ?? $container->load('getConsole_Messenger_ExecuteCommandHandlerService')), ['sign' => true]);
    }
}
