<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgent_Execution_Bus_Messenger_HandlersLocatorService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'agent.execution.bus.messenger.handlers_locator' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlersLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocator.php';

        $instance = new \Symfony\Component\Messenger\Handler\HandlersLocator(['Ineersa\\AgentCore\\Domain\\Message\\ExecuteLlmStep' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.hicAqfE'] ?? $container->load('get_Messenger_HandlerDescriptor_HicAqfEService'));
        }, 1), 'Ineersa\\AgentCore\\Domain\\Message\\ExecuteToolCall' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.9JusjcH'] ?? $container->load('get_Messenger_HandlerDescriptor_9JusjcHService'));
        }, 1), 'Symfony\\Component\\Process\\Messenger\\RunProcessMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.2IYpJH8'] ?? $container->load('get_Messenger_HandlerDescriptor_2IYpJH8Service'));
        }, 1), 'Symfony\\Component\\Console\\Messenger\\RunCommandMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.Jfy4_s8'] ?? $container->load('get_Messenger_HandlerDescriptor_Jfy4S8Service'));
        }, 1), 'Symfony\\Component\\HttpClient\\Messenger\\PingWebhookMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.mD3SEQf'] ?? $container->load('get_Messenger_HandlerDescriptor_MD3SEQfService'));
        }, 1), 'Symfony\\Component\\Scheduler\\Messenger\\ServiceCallMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.mdnjiVd'] ?? $container->load('get_Messenger_HandlerDescriptor_MdnjiVdService'));
        }, 1), 'Symfony\\Component\\Messenger\\Message\\RedispatchMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.ARP4Civ'] ?? $container->load('get_Messenger_HandlerDescriptor_ARP4CivService'));
        }, 1)]);

        if (isset($container->privates['agent.execution.bus.messenger.handlers_locator'])) {
            return $container->privates['agent.execution.bus.messenger.handlers_locator'];
        }

        return $container->privates['agent.execution.bus.messenger.handlers_locator'] = $instance;
    }
}
