<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditFileToolService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Tool\EditFileTool' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Tool\EditFileTool
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Tool/HatfieldToolProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Tool/ToolHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Tool/EditFileTool.php';

        return $container->privates['Ineersa\\CodingAgent\\Tool\\EditFileTool'] = new \Ineersa\CodingAgent\Tool\EditFileTool(($container->privates['Ineersa\\CodingAgent\\Tool\\ToolRuntime'] ?? $container->load('getToolRuntimeService')));
    }
}
