<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileMentionIndexReaderService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\Tui\Completion\FileMentionIndexReader' shared autowired service.
     *
     * @return \Ineersa\Tui\Completion\FileMentionIndexReader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Tui/Completion/FileMentionIndexReader.php';

        return $container->privates['Ineersa\\Tui\\Completion\\FileMentionIndexReader'] = new \Ineersa\Tui\Completion\FileMentionIndexReader($container->getEnv('string:default:kernel.project_dir:string:HATFIELD_CWD').'/.hatfield/cache/file-mentions/index.jsonl');
    }
}
