<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHatfieldModelCatalogService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Config\Ai\HatfieldModelCatalog' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Config\Ai\HatfieldModelCatalog
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Config/Ai/HatfieldModelCatalog.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Config/Ai/AiConfig.php';

        return $container->privates['Ineersa\\CodingAgent\\Config\\Ai\\HatfieldModelCatalog'] = new \Ineersa\CodingAgent\Config\Ai\HatfieldModelCatalog(($container->privates['Ineersa\\CodingAgent\\Config\\Ai\\AiConfig'] ??= new \Ineersa\CodingAgent\Config\Ai\AiConfig()));
    }
}
