<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageGatingConvertHookService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Tool\ImageProcessing\ImageGatingConvertHook' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Tool\ImageProcessing\ImageGatingConvertHook
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Contract/Hook/ConvertToLlmHookInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Tool/ImageProcessing/ImageGatingConvertHook.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Infrastructure/SymfonyAi/AgentMessageConverter.php';

        return $container->privates['Ineersa\\CodingAgent\\Tool\\ImageProcessing\\ImageGatingConvertHook'] = new \Ineersa\CodingAgent\Tool\ImageProcessing\ImageGatingConvertHook(($container->privates['Ineersa\\CodingAgent\\Tool\\ImageProcessing\\CodingAgentImageCapabilityChecker'] ?? $container->load('getCodingAgentImageCapabilityCheckerService')), ($container->privates['Ineersa\\AgentCore\\Infrastructure\\SymfonyAi\\AgentMessageConverter'] ??= new \Ineersa\AgentCore\Infrastructure\SymfonyAi\AgentMessageConverter()));
    }
}
