<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLlmStreamDispatchObserverService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\CodingAgent\Runtime\Stream\LlmStreamDispatchObserver' shared autowired service.
     *
     * @return \Ineersa\CodingAgent\Runtime\Stream\LlmStreamDispatchObserver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Contract/Hook/LlmStreamObserverInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Runtime/Stream/LlmStreamDispatchObserver.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['Ineersa\\CodingAgent\\Runtime\\Stream\\LlmStreamDispatchObserver'])) {
            return $container->privates['Ineersa\\CodingAgent\\Runtime\\Stream\\LlmStreamDispatchObserver'];
        }

        $instance = new \Ineersa\CodingAgent\Runtime\Stream\LlmStreamDispatchObserver($a);

        if (isset($container->privates['Ineersa\\CodingAgent\\Runtime\\Stream\\LlmStreamDispatchObserver'])) {
            return $container->privates['Ineersa\\CodingAgent\\Runtime\\Stream\\LlmStreamDispatchObserver'];
        }

        return $container->privates['Ineersa\\CodingAgent\\Runtime\\Stream\\LlmStreamDispatchObserver'] = $instance;
    }
}
