<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRunTracerService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\AgentCore\Application\Handler\RunTracer' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Handler\RunTracer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Handler/RunTracer.php';
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Contract/SpanProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CodingAgent/Logging/DdtraceSpanProvider.php';

        return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\RunTracer'] = new \Ineersa\AgentCore\Application\Handler\RunTracer(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->privates['Ineersa\\CodingAgent\\Logging\\DdtraceSpanProvider'] ??= new \Ineersa\CodingAgent\Logging\DdtraceSpanProvider()));
    }
}
