<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToolExecutionResultStoreService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ineersa\AgentCore\Application\Handler\ToolExecutionResultStore' shared autowired service.
     *
     * @return \Ineersa\AgentCore\Application\Handler\ToolExecutionResultStore
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AgentCore/Application/Handler/ToolExecutionResultStore.php';

        return $container->privates['Ineersa\\AgentCore\\Application\\Handler\\ToolExecutionResultStore'] = new \Ineersa\AgentCore\Application\Handler\ToolExecutionResultStore();
    }
}
