<?php

namespace ContainerV2CSdrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getValidator_ExpressionLanguageService extends Ineersa_CodingAgent_KernelTestDebugContainer
{
    /**
     * Gets the private 'validator.expression_language' shared service.
     *
     * @return \Symfony\Component\ExpressionLanguage\ExpressionLanguage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/expression-language/ExpressionFunctionProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/Constraints/ExpressionLanguageProvider.php';

        $a = ($container->privates['cache.validator_expression_language'] ?? $container->load('getCache_ValidatorExpressionLanguageService'));

        if (isset($container->privates['validator.expression_language'])) {
            return $container->privates['validator.expression_language'];
        }

        $instance = new \Symfony\Component\ExpressionLanguage\ExpressionLanguage($a);

        if (isset($container->privates['validator.expression_language'])) {
            return $container->privates['validator.expression_language'];
        }

        $container->privates['validator.expression_language'] = $instance;

        $instance->registerProvider(($container->privates['validator.expression_language_provider'] ??= new \Symfony\Component\Validator\Constraints\ExpressionLanguageProvider()));

        return $instance;
    }
}
