<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCKKBfsx\Ineersa_CodingAgent_KernelTestContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCKKBfsx/Ineersa_CodingAgent_KernelTestContainer.php') {
    touch(__DIR__.'/ContainerCKKBfsx.legacy');

    return;
}

if (!\class_exists(Ineersa_CodingAgent_KernelTestContainer::class, false)) {
    \class_alias(\ContainerCKKBfsx\Ineersa_CodingAgent_KernelTestContainer::class, Ineersa_CodingAgent_KernelTestContainer::class, false);
}

return new \ContainerCKKBfsx\Ineersa_CodingAgent_KernelTestContainer([
    'container.build_hash' => 'CKKBfsx',
    'container.build_id' => '79daec24',
    'container.build_time' => 1781124687,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCKKBfsx');
