<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLwFcCHH\Ineersa_CodingAgent_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLwFcCHH/Ineersa_CodingAgent_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerLwFcCHH.legacy');

    return;
}

if (!\class_exists(Ineersa_CodingAgent_KernelProdContainer::class, false)) {
    \class_alias(\ContainerLwFcCHH\Ineersa_CodingAgent_KernelProdContainer::class, Ineersa_CodingAgent_KernelProdContainer::class, false);
}

return new \ContainerLwFcCHH\Ineersa_CodingAgent_KernelProdContainer([
    'container.build_hash' => 'LwFcCHH',
    'container.build_id' => 'cc5891a3',
    'container.build_time' => 1781124688,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLwFcCHH');
