<?php

declare(strict_types=1);

namespace Ineersa\CodingAgent\Tests\Runtime\Controller\E2E\Replay;

/**
 * Test-only console wrapper for controller/TUI replay Messenger consumers.
 *
 * ConsumerSupervisor (and TUI process transport) resolve the app binary via
 * HATFIELD_BINARY_PATH / ConfigExecutableLocator. Symfony's default idle
 * `--sleep` is 1s, which adds multi-second queue lag on SafeGuard multi-hop
 * and tool-start paths under concurrent Castor load. This wrapper:
 * - requires the real source `bin/console`
 * - injects a small explicit `--sleep` only for `messenger:consume`
 * - passes through all other commands unchanged (e.g. `agent --controller`)
 *
 * Security: lives under the isolated E2E temp tree, is not production code,
 * never shells out, and fails loudly only when the source console is missing.
 */
final class ControllerReplayLowLatencyMessengerConsole
{
    public const string SLEEP_SECONDS = '0.05';

    /**
     * Write an absolute wrapper path under $tempDir and return it for
     * HATFIELD_BINARY_PATH.
     */
    public static function install(string $tempDir, string $sourceConsolePath): string
    {
        if (!is_file($sourceConsolePath) || !is_readable($sourceConsolePath)) {
            throw new \RuntimeException('Source console is missing or unreadable: '.$sourceConsolePath);
        }

        $realConsole = realpath($sourceConsolePath);
        if (false === $realConsole) {
            throw new \RuntimeException('Unable to resolve source console path: '.$sourceConsolePath);
        }

        $dir = $tempDir.'/.hatfield/tmp';
        if (!is_dir($dir) && !mkdir($dir, 0o777, true) && !is_dir($dir)) {
            throw new \RuntimeException('Unable to create wrapper directory: '.$dir);
        }

        $wrapperPath = $dir.'/controller-replay-messenger-console.php';
        $sleep = self::SLEEP_SECONDS;
        $consoleExport = var_export($realConsole, true);

        $wrapper = <<<PHP
#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Auto-generated by ControllerReplayLowLatencyMessengerConsole.
 * For messenger:consume, injects --sleep={$sleep}; otherwise pass-through.
 */

\$sourceConsole = {$consoleExport};
\$argv = \$_SERVER['argv'] ?? [];
if ([] === \$argv) {
    fwrite(STDERR, "controller-replay messenger console wrapper: empty argv\\n");
    exit(1);
}

// Drop wrapper path (argv0); remaining args are console command + options.
array_shift(\$argv);

\$isConsume = false;
foreach (\$argv as \$arg) {
    if ('messenger:consume' === \$arg) {
        \$isConsume = true;
        break;
    }
}

if (\$isConsume) {
    \$hasSleep = false;
    foreach (\$argv as \$arg) {
        \$arg = (string) \$arg;
        if ('--sleep' === \$arg || str_starts_with(\$arg, '--sleep=')) {
            \$hasSleep = true;
            break;
        }
    }
    if (!\$hasSleep) {
        \$argv[] = '--sleep={$sleep}';
    }
}

\$_SERVER['argv'] = array_values(array_merge([\$sourceConsole], \$argv));
\$_SERVER['argc'] = count(\$_SERVER['argv']);
\$GLOBALS['argv'] = \$_SERVER['argv'];
\$GLOBALS['argc'] = \$_SERVER['argc'];

require \$sourceConsole;
PHP;

        if (false === file_put_contents($wrapperPath, $wrapper)) {
            throw new \RuntimeException('Unable to write messenger console wrapper: '.$wrapperPath);
        }

        @chmod($wrapperPath, 0o755);

        $absolute = realpath($wrapperPath);
        if (false === $absolute || !is_readable($absolute)) {
            throw new \RuntimeException('Messenger console wrapper is not readable: '.$wrapperPath);
        }

        return $absolute;
    }
}
