<?php

declare(strict_types=1);

namespace Ineersa\AgentCore\Contract\Tool;

/**
 * AgentCore-owned seam for resolving a per-turn tool reference into an
 * active toolset snapshot.
 *
 * The concrete implementation belongs to the CodingAgent layer (or
 * whatever app layer owns the ToolRegistry), so AgentCore remains
 * generic. AgentCore generates toolsRef strings and passes them through
 * the platform invocation path; this resolver bridges from the opaque
 * reference back to the active tool names and execution allowlist.
 */
interface ToolSetResolverInterface
{
    /**
     * Resolve a toolsRef (plus optional run/turn context) to an active
     * toolset snapshot.
     *
     * @param string      $toolsRef Opaque toolset reference generated by AgentCore
     *                              (e.g. "toolset:run:{runId}:turn:{turnNo}")
     * @param int|null    $turnNo   Current turn number (may help driver resolution)
     * @param string|null $runId    Current run identity
     *
     * @return ActiveToolSet resolved snapshot; an empty set is returned when
     *                       the reference cannot be resolved rather than throwing
     */
    public function resolve(string $toolsRef, ?int $turnNo = null, ?string $runId = null): ActiveToolSet;
}
